
export enum DomesticFormat {
    T20 = 'T20',
    LIST_A = 'List A',
    FC = 'FC'
}

export enum InternationalFormat {
    TEST = 'Test',
    ODI = 'ODI',
    T20I = 'T20i'
}

export enum Format {
    T20 = 'Premier T20 League',
    ODI = 'Premier One-Day Cup',
    SHIELD = 'Premier First-Class Shield',
    FIRST_CLASS = 'Premier First-Class Shield',
    WLT20 = 'World League T20',
    DEVELOPMENT_T20 = 'Development T20 Cup',
    DEVELOPMENT_ODI = 'Development List-A Cup',
    DEVELOPMENT_FIRST_CLASS = 'Development First-Class Cup',
    RISE_T20 = 'Rise T20 Cup',
    RISE_ODI = 'Rise List-A Cup',
    RISE_FIRST_CLASS = 'Rise First-Class Cup'
}

export enum PlayerRole {
    BATSMAN = 'BT',
    WICKET_KEEPER = 'WK',
    ALL_ROUNDER = 'AR',
    SPIN_BOWLER = 'SB',
    FAST_BOWLER = 'BL',
}

export interface RawPlayerData {
    id: string;
    name: string;
    age: number;
    nationality: string;
    role: string;
    batting: number;
    bowling: number;
    style: string;
    isForeign: boolean;
    pos?: string;
    weakness?: string;
    traits?: string[];
}

export type BattingStyle = 'A' | 'D' | 'N' | 'NA';
export type Strategy = 'defensive' | 'balanced' | 'attacking';
export type AppState = 'MAIN_MENU' | 'TEAM_SELECTION' | 'AUCTION' | 'CAREER_HUB';
export type CareerScreen = 'DASHBOARD' | 'LEAGUES' | 'LINEUPS' | 'EDITOR' | 'NEWS' | 'STATS' | 'SETTINGS' | 'PLAYER_PROFILE' | 'MATCH_RESULT' | 'FORWARD_RESULTS' | 'AWARDS_RECORDS' | 'TRANSFERS' | 'END_OF_FORMAT' | 'COMPARISON' | 'SCHEDULE' | 'LIVE_MATCH' | 'SPONSOR_ROOM' | 'CUSTOMIZATION' | 'SELECT_PLAYER_FOR_COMPARISON_SLOT_1' | 'SELECT_PLAYER_FOR_COMPARISON_SLOT_2' | 'AUCTION_ROOM' | 'RETENTION' | 'PLAYER_DATABASE' | 'SIKE_SHARE' | 'CHAMPIONS_LEAGUE' | 'WORLD_LEAGUE' | 'SEASON_TRANSITION' | 'SHOT_SELECTION' | 'SERIES_MANAGER' | 'CALENDAR' | 'RANKINGS' | 'SEASON_STANDINGS';

export type MajorTournamentType = 'ODI World Cup' | 'T20 World Cup' | 'Champions Trophy' | 'World Test Championship Final';
export type RankingFormat = 'Test' | 'ODI' | 'T20';

export interface GameDate {
    year: number;
    month: number; // 1-12
    day: number;   // 1-30
}

export interface SeriesFormatMatchConfig {
    format: 'T20' | 'ODI' | 'Test';
    count: number;
}

export interface Series {
    id: string;
    name: string;
    teamA: string;
    teamB: string;
    teamAId?: string;
    teamBId?: string;
    format: 'T20' | 'ODI' | 'Test' | 'Multi-Format' | Format | string;
    formatsIncluded?: ('T20' | 'ODI' | 'Test')[];
    formatBreakdown?: SeriesFormatMatchConfig[];
    startDate: GameDate;
    endDate: GameDate;
    numberOfMatches: number;
    status: 'upcoming' | 'live' | 'completed';
    restDays?: number;
    autoGenerated?: boolean;
    tierCategory?: 'same-tier' | 'adjacent-tier' | 'cross-tier';
    seriesScore?: {
        teamAWins: number;
        teamBWins: number;
        draws: number;
        ties: number;
    };
    winnerTeamId?: string | null;
}

export interface CurrentYearStanding {
    teamId: string;
    teamName: string;
    seriesPlayed: number;
    seriesWon: number;
    seriesLost: number;
    seriesDrawn: number;
    points: number; // Win = 2, Draw/Tie = 1, Loss = 0
    matchesPlayed: number;
    matchesWon: number;
    matchesLost: number;
    matchesTiedOrDrawn: number;
    rank?: number;
    byFormat?: {
        Test: { seriesPlayed: number; seriesWon: number; seriesLost: number; seriesDrawn: number; points: number; matchesPlayed: number; matchesWon: number; matchesLost: number; matchesDrawn: number };
        ODI: { seriesPlayed: number; seriesWon: number; seriesLost: number; seriesDrawn: number; points: number; matchesPlayed: number; matchesWon: number; matchesLost: number; matchesTied: number };
        T20: { seriesPlayed: number; seriesWon: number; seriesLost: number; seriesDrawn: number; points: number; matchesPlayed: number; matchesWon: number; matchesLost: number; matchesTied: number };
    };
}

export interface ScheduledEvent {
    id: string;
    name: string;
    type: 'tournament' | 'series' | 'major_tournament' | 'rest';
    format: Format | string;
    startDate: GameDate;
    endDate: GameDate;
    description?: string;
    teamA?: string;
    teamB?: string;
    matchCount?: number;
    restDays?: number;
    isMonth12Locked?: boolean;
}

export interface TeamRanking {
    teamId: string;
    teamName: string;
    rating: number;
    matchesPlayed: number;
    points: number;
    rank: number;
    previousRank: number;
}

export interface PlayerRanking {
    playerId: string;
    playerName: string;
    teamName: string;
    role: PlayerRole;
    rating: number;
    rank: number;
    previousRank: number;
}

export interface FormatPlayerRankings {
    batting: PlayerRanking[];
    bowling: PlayerRanking[];
    allRounder: PlayerRanking[];
}

export interface PlayerStats {
    matches: number; 
    inningsBatting: number;
    inningsBowling: number;
    runs: number; highestScore: number; average: number; strikeRate: number; ballsFaced: number; dismissals: number;
    hundreds: number; fifties: number; thirties: number; fours: number; sixes: number; fastestFifty: number; fastestHundred: number;
    wickets: number; economy: number; bestBowling: string; bestBowlingWickets: number; bestBowlingRuns: number; bowlingAverage: number;
    ballsBowled: number; runsConceded: number; threeWicketHauls: number; fiveWicketHauls: number; catches: number; runOuts: number;
    manOfTheMatchAwards: number;
    phaseStats?: {
        batting: {
            pp: { runs: number; balls: number; dismissals: number };
            mo: { runs: number; balls: number; dismissals: number };
            do: { runs: number; balls: number; dismissals: number };
        };
        bowling: {
            pp: { wickets: number; runsConceded: number; ballsBowled: number };
            mo: { wickets: number; runsConceded: number; ballsBowled: number };
            do: { wickets: number; runsConceded: number; ballsBowled: number };
        };
    };
    positionStats?: Record<number, {
        innings: number;
        runs: number;
        balls: number;
        dismissals: number;
        thirties: number;
        fifties: number;
        hundreds: number;
    }>;
}

export interface PlayerInjury {
    durationType: 'matches' | 'seasons';
    durationValue: number;
    text: string;
}

export type BowlingSubType = 'ls' | 'os' | 'lals' | 'laos' | 'lac' | 'mv' | 'fb' | 'fbs' | 'm' | 'none';

export interface PlayerSeasonEvaluation {
    season: number;
    totalScore: number; // 0 - 100
    battingScore: number; // 0 - 100
    bowlingScore: number; // 0 - 100
    fieldingScore: number; // 0 - 100
    runs: number;
    average: number;
    strikeRate: number;
    fifties: number;
    hundreds: number;
    highestScore: number;
    consistencyRating: number;
    matchWinningInnings: number;
    wickets: number;
    economy: number;
    bowlingAverage: number;
    bowlingStrikeRate: number;
    fourWicketHauls: number;
    fiveWicketHauls: number;
    powerplayRating: number;
    deathOverRating: number;
    catches: number;
    runOuts: number;
    stumpings: number;
    fieldingEfficiency: number;
    grade: 'S+' | 'S' | 'A+' | 'A' | 'B+' | 'B' | 'C' | 'D';
}

export interface Player {
    id: string; name: string; age: number; nationality: string; role: PlayerRole; battingSkill: number; secondarySkill: number;
    style: BattingStyle; isOpener: boolean; isForeign: boolean; teamName?: string;
    image?: string;
    avatar?: string;
    customProfiles?: { [key in Format]?: { avg: number; sr: number } };
    stats: Record<Format | string, PlayerStats>;
    domesticStats?: Record<DomesticFormat | 'T20' | 'List A' | 'FC' | string, PlayerStats>;
    internationalStats?: Record<InternationalFormat | 'Test' | 'ODI' | 'T20i' | string, PlayerStats>;
    injury?: PlayerInjury | null;
    badges?: string[];
    healthStatus?: 'fit' | 'injured' | 'temporary_fit';
    injuryType?: string | null;
    injuryMatchesRemaining?: number;
    injurySeasonsRemaining?: number;
    fitness?: number;
    basePrice?: number;
    bowlingSubType?: BowlingSubType;
    weaknesses?: BowlingSubType[];
    isFinisher?: boolean;
    isPowerHitter?: boolean;
    isMiddleOrder?: boolean;
    isPowerplayBowler?: boolean;
    isDeathBowler?: boolean;
    subRole?: string;
    potential?: number; // 60 - 99
    form?: number; // 50 - 99
    previousSeasonPerformance?: number; // 0 - 100 score from last season
    championsLeaguePerformance?: number; // 0 - 100 score in premier competitions
    worldLeaguePerformance?: number; // 0 - 100 score in premier World League competitions
    worldLeagueStats?: PlayerStats; // Specific stats accumulated during World League tournament
    seasonPerformanceScore?: PlayerSeasonEvaluation;
    seasonEvaluationsHistory?: Record<number, PlayerSeasonEvaluation>;
    performanceHistory?: {
        [key in Format]?: {
            matchNumber: string | number;
            battingAverage: number;
            bowlingEconomy: number;
        }[];
    };
    trophies?: {
        worldCupsWon?: number;
        t20WorldCupsWon?: number;
        championsTrophiesWon?: number;
        wtcTitlesWon?: number;
        [key: string]: number | undefined;
    };
}

export interface Team {
    id: string; name: string; squad: Player[]; captains: { [key in Format]?: string };
    viceCaptains?: { [key in Format]?: string };
    purse: number; // In PKR Crore (stored as number, e.g., 50.0)
    firstAidKits?: number;
    firstAidAvailable?: boolean;
    captainId?: string | null;
    viceCaptainId?: string | null;
    trophies?: {
        worldCupsWon?: number;
        t20WorldCupsWon?: number;
        championsTrophiesWon?: number;
        wtcTitlesWon?: number;
        [key: string]: number | undefined;
    };
}

export interface TeamData {
    id: string; name: string; homeGround: string; logo: string; isYouthTeam: boolean;
}

export interface Ground {
    name: string; code: string; pitch: string; dimensions?: string; weather?: 'Sunny' | 'Overcast' | 'Rainy' | 'Humid' | 'Dry';
    boundarySize?: 'Small' | 'Medium' | 'Large'; outfieldSpeed?: 'Fast' | 'Medium' | 'Slow' | 'Lightning'; capacity?: number;
}

export interface Match {
    matchNumber: number | string;
    teamA: string;
    teamAId?: string;
    vs: string;
    teamB: string;
    teamBId?: string;
    date: string;
    group: 'Round-Robin' | 'Semi-Finals' | 'Final' | 'Group A' | 'Group B' | 'Series' | string;
    seriesId?: string;
    seriesName?: string;
    scheduledDate?: GameDate;
    daysPlayed?: number;
    format?: Format | string;
    stage?: string;
    tournamentName?: string;
    venue?: string;
    result?: MatchResult;
}

export interface Inning {
    teamId: string; teamName: string; score: number; wickets: number; overs: string; batting: BattingPerformance[]; bowling: BowlingPerformance[]; extras: number; recentBalls?: string[];
    ppRuns?: number; ppWickets?: number; ppBalls?: number; ppDots?: number; ppFours?: number; ppSixes?: number;
    moRuns?: number; moWickets?: number; moBalls?: number; moDots?: number; moFours?: number; moSixes?: number;
    doRuns?: number; doWickets?: number; doBalls?: number; doDots?: number; doFours?: number; doSixes?: number;
    [key: string]: any;
}

export interface BattingPerformance {
    playerId: string; playerName: string; runs: number; balls: number; fours: number; sixes: number; isOut: boolean; dismissalText: string; dismissal: { type: 'not out' | 'bowled' | 'caught'; bowlerId: string; fielderId?: string; }; ballsToFifty?: number; ballsToHundred?: number;
    ppRuns?: number; ppBalls?: number; ppDismissals?: number;
    moRuns?: number; moBalls?: number; moDismissals?: number;
    doRuns?: number; doBalls?: number; doDismissals?: number;
    battingPosition?: number;
    injury?: PlayerInjury | null; healthStatus?: 'fit' | 'injured' | 'temporary_fit';
}

export interface BowlingPerformance {
    playerId: string; playerName: string; overs: string; maidens: number; runsConceded: number; wickets: number; ballsBowled: number;
    ppWickets?: number; ppRunsConceded?: number; ppBallsBowled?: number;
    moWickets?: number; moRunsConceded?: number; moBallsBowled?: number;
    doWickets?: number; doRunsConceded?: number; doBallsBowled?: number;
    injury?: PlayerInjury | null; healthStatus?: 'fit' | 'injured' | 'temporary_fit';
}

export interface MatchResult {
    matchNumber: number | string;
    format?: Format;
    season?: number;
    winnerId: string | null;
    loserId: string | null;
    isDraw?: boolean;
    isTie?: boolean;
    seriesId?: string;
    summary: string;
    firstInning: Inning;
    secondInning: Inning;
    thirdInning?: Inning;
    fourthInning?: Inning;
    manOfTheMatch: { playerId: string; playerName: string; teamId: string; summary: string; };
    tossWinnerId?: string;
    tossDecision?: 'bat' | 'bowl';
    highlights?: string[];
    teamACaptainId?: string;
    teamBCaptainId?: string;
}

export interface Standing {
    teamId: string; teamName: string; played: number; won: number; lost: number; drawn: number; points: number; netRunRate: number; runsFor?: number; runsAgainst?: number;
}

export interface NewsArticle {
    id: string;
    headline: string;
    date: string;
    excerpt: string;
    content: string;
    type?: 'match' | 'transfer' | 'league' | 'squad' | 'milestone' | 'record' | 'performance' | 'form' | 'h2h';
    priority?: 'major' | 'important' | 'normal';
    category?: 'Team Performance' | 'Player Impact' | 'Form Watch' | 'Record Breaker' | 'Head-to-Head' | 'Career Milestone' | 'Tournament & Draft';
    relatedPlayerId?: string;
    relatedPlayerName?: string;
    relatedTeamId?: string;
    relatedTeamName?: string;
    milestoneKey?: string;
}

export interface Award {
    season: number; format: Format; winnerTeamId: string; winnerTeamName: string;
    playerOfSeason?: { playerId: string, playerName: string, teamName: string, impact: number };
    bestBatter: { playerId: string, playerName: string, teamName: string, runs: number };
    bestBowler: { playerId: string, playerName: string, teamName: string, wickets: number };
    powerHitter?: { playerId: string, playerName: string, teamName: string, sixes: number };
}

export interface HallOfFameInductee {
    season: number;
    roleCategory: 'BATTER' | 'BOWLER' | 'ALL_ROUNDER' | 'FOREIGN';
    playerId: string;
    playerName: string;
    teamName: string;
    nationality: string;
    isForeign: boolean;
    role: PlayerRole;
    statsSummary: string;
    achievements: string[];
    skillSnapshot: {
        battingSkill: number;
        bowlingSkill: number;
    };
    iconBadge?: string;
    seasonRuns?: number;
    seasonWickets?: number;
    battingAverage?: number;
    bowlingEconomy?: number;
    evaluationScore?: number;
    achievementHighlight?: string;
}

export interface SeasonHallOfFame {
    season: number;
    bestBatter: HallOfFameInductee;
    bestBowler: HallOfFameInductee;
    bestAllRounder: HallOfFameInductee;
    bestForeign: HallOfFameInductee;
}

export interface TeamOfTheSeasonPlayer {
    player: Player;
    position: number; // 1 to 11
    assignedRole: 'Opener' | 'Top Order' | 'Middle Order' | 'Wicket Keeper' | 'All-Rounder' | 'Pace Bowler' | 'Spin Bowler';
    isCaptain?: boolean;
    isWicketKeeper?: boolean;
    isForeign?: boolean;
    seasonRuns?: number;
    seasonWickets?: number;
    seasonAvg?: number;
    seasonSrOrEcon?: number;
    seasonScore?: number;
}

export interface SeasonTeamsOfTournament {
    season: number;
    format: Format;
    autoTeamOfTheTournament: {
        players: TeamOfTheSeasonPlayer[];
        captainId: string;
        wicketKeeperId: string;
        foreignCount: number;
    };
    userTeamOfTheSeason?: {
        players: TeamOfTheSeasonPlayer[];
        captainId: string;
        wicketKeeperId: string;
        scoreSynergy?: number;
        submittedAt?: string;
        consensusMatchesWithAuto?: number;
    };
}

export interface SkillProgressionReport {
    playerId: string;
    playerName: string;
    teamName: string;
    role: PlayerRole;
    roleCategory: 'BATTER' | 'BOWLER' | 'ALL_ROUNDER';
    changeType: 'GAIN' | 'LOSS';
    rank: number; // 1 to 10
    battingSkillDelta: number;
    bowlingSkillDelta: number;
    oldBattingSkill: number;
    newBattingSkill: number;
    oldBowlingSkill: number;
    newBowlingSkill: number;
    reason: string;
    age?: number;
    isForeign?: boolean;
    seasonEvaluationScore?: number;
}

export interface SkillProgressionSummary {
    season: number;
    gainingBatters: SkillProgressionReport[];
    losingBatters: SkillProgressionReport[];
    gainingBowlers: SkillProgressionReport[];
    losingBowlers: SkillProgressionReport[];
    gainingAllRounders: SkillProgressionReport[];
    losingAllRounders: SkillProgressionReport[];
}

export interface ScoreLimits { maxRuns?: number; maxWickets?: number; }
export type InningLimits = { [key: number]: ScoreLimits; };

export interface UniversalFilterState {
    format: 'ALL' | Format;
    season: 'ALL' | number;
    teamId: 'ALL' | string;
    opponentTeamId: 'ALL' | string;
    tournament: 'ALL' | string;
    role: 'ALL' | 'CAPTAIN' | 'PLAYER';
}

export interface CaptaincyFormatStats {
    formatName: string;
    matches: number;
    wins: number;
    losses: number;
    ties: number;
    noResults: number;
    winPct: number;
    lossPct: number;
    runs: number;
    battingAverage: number;
    strikeRate: number;
    wickets: number;
    bowlingAverage: number;
    economy: number;
    highestScore: number;
    bestBowling: string;
}

export interface CaptaincyRecord {
    totalMatches: number;
    wins: number;
    losses: number;
    ties: number;
    noResults: number;
    winPct: number;
    lossPct: number;
    winningStreak: number;
    losingStreak: number;
    highestTeamScore: { score: number; wickets: number; overs: string; vsTeamName: string; date?: string; matchNum?: string };
    lowestTeamScore: { score: number; wickets: number; overs: string; vsTeamName: string; date?: string; matchNum?: string };
    highestSuccessfulChase: { target: number; score: number; wickets: number; vsTeamName: string; date?: string };
    biggestWin: { marginText: string; vsTeamName: string; format?: string; date?: string };
    biggestDefeat: { marginText: string; vsTeamName: string; format?: string; date?: string };
    byFormat: Record<string, CaptaincyFormatStats>;
}

export interface PlayerVsTeamDetailed {
    vsTeamId: string;
    vsTeamName: string;
    batting: {
        matches: number;
        innings: number;
        runs: number;
        average: number;
        strikeRate: number;
        highestScore: number;
        lowestScore: number;
        fifties: number;
        hundreds: number;
        fours: number;
        sixes: number;
        notOuts: number;
    };
    bowling: {
        matches: number;
        overs: string;
        ballsBowled: number;
        runsConceded: number;
        wickets: number;
        bowlingAverage: number;
        economy: number;
        bestBowling: string;
        threeWickets: number;
        fiveWickets: number;
    };
    captaincy: {
        matches: number;
        wins: number;
        losses: number;
    };
}

export interface PlayerTeamHistoryRecord {
    teamId: string;
    teamName: string;
    seasons: number[];
    matches: number;
    runs: number;
    wickets: number;
    battingAverage: number;
    bowlingAverage: number;
    captaincyMatches: number;
    captaincyWins: number;
    captaincyLosses: number;
}

export interface TeamVsTeamMatchExtremes {
    highestScoringMatch: { totalRuns: number; teamAScore: string; teamBScore: string; summary: string };
    lowestScoringMatch: { totalRuns: number; teamAScore: string; teamBScore: string; summary: string };
    biggestWinByRuns: { winnerName: string; margin: number; summary: string };
    biggestWinByWickets: { winnerName: string; margin: number; summary: string };
    closestWin: { winnerName: string; marginText: string; summary: string };
}

export interface TeamHeadToHeadBattingStats {
    teamId: string;
    teamName: string;
    highestScore: { score: number; wickets: number; overs: string };
    lowestScore: { score: number; wickets: number; overs: string };
    highestSuccessfulChase: { target: number; score: number; wickets: number };
    mostRunsInOneInnings: { score: number; wickets: number };
    biggestTeamTotal: number;
}

export interface HeadToHeadDetailed {
    teamA: { id: string; name: string };
    teamB: { id: string; name: string };
    totalMatches: number;
    winsA: number;
    winsB: number;
    ties: number;
    noResults: number;
    winPctA: number;
    winPctB: number;
    currentWinningStreak: { teamName: string; count: number };
    longestStreakA: number;
    longestStreakB: number;
    battingRecordsA: TeamHeadToHeadBattingStats;
    battingRecordsB: TeamHeadToHeadBattingStats;
    extremes: TeamVsTeamMatchExtremes;
}

export interface BestBatterAgainstTeam {
    playerId: string;
    playerName: string;
    teamName: string;
    matches: number;
    innings: number;
    runs: number;
    average: number;
    strikeRate: number;
    highestScore: number;
    fifties: number;
    hundreds: number;
    fours: number;
    sixes: number;
}

export interface BestBowlerAgainstTeam {
    playerId: string;
    playerName: string;
    teamName: string;
    matches: number;
    overs: string;
    ballsBowled: number;
    runsConceded: number;
    wickets: number;
    bowlingAverage: number;
    economy: number;
    bestBowling: string;
    fourWicketHauls: number;
    fiveWicketHauls: number;
}

export interface PlayerVsPlayerMatchupRecord {
    batterId: string;
    batterName: string;
    bowlerId: string;
    bowlerName: string;
    ballsFaced: number;
    runs: number;
    boundaries: number;
    sixes: number;
    dotBalls: number;
    strikeRate: number;
    dismissals: number;
}

export interface TeamComprehensiveRecords {
    teamId: string;
    teamName: string;
    batting: {
        highestScore: { score: number; wickets: number; overs: string; vsTeam: string; format?: string };
        lowestScore: { score: number; wickets: number; overs: string; vsTeam: string; format?: string };
        highestSuccessfulChase: { target: number; score: number; wickets: number; vsTeam: string };
        mostRunsInASeason: { runs: number; season: number };
        mostTeam6s: number;
        mostTeam4s: number;
        highestPartnership: { runs: number; player1: string; player2: string; vsTeam: string };
        highestIndividualScore: { runs: number; playerName: string; vsTeam: string };
    };
    bowling: {
        bestBowlingInnings: { figures: string; playerName: string; vsTeam: string };
        mostWicketsInMatch: { wickets: number; playerName: string; vsTeam: string };
        mostWicketsInASeason: { wickets: number; season: number };
        bestEconomy: { economy: number; playerName: string; overs: string; vsTeam: string };
        most5WicketHauls: { count: number; playerName: string };
    };
    match: {
        biggestWinByRuns: { margin: number; vsTeam: string; summary: string };
        biggestWinByWickets: { margin: number; vsTeam: string; summary: string };
        biggestDefeat: { marginText: string; vsTeam: string; summary: string };
        closestVictory: { marginText: string; vsTeam: string; summary: string };
        longestWinningStreak: number;
        longestLosingStreak: number;
    };
}

export interface AllTimeCareerRecords {
    batting: {
        mostCareerRuns: { playerId: string; playerName: string; teamName: string; runs: number }[];
        mostRunsInASeason: { playerId: string; playerName: string; teamName: string; season: number; runs: number }[];
        highestScore: { playerId: string; playerName: string; teamName: string; score: number; vsTeam: string }[];
        mostCenturies: { playerId: string; playerName: string; teamName: string; count: number }[];
        mostFifties: { playerId: string; playerName: string; teamName: string; count: number }[];
        mostSixes: { playerId: string; playerName: string; teamName: string; count: number }[];
        mostFours: { playerId: string; playerName: string; teamName: string; count: number }[];
    };
    bowling: {
        mostCareerWickets: { playerId: string; playerName: string; teamName: string; wickets: number }[];
        mostWicketsInASeason: { playerId: string; playerName: string; teamName: string; season: number; wickets: number }[];
        bestBowlingFigures: { playerId: string; playerName: string; teamName: string; figures: string; vsTeam: string }[];
        most5WicketHauls: { playerId: string; playerName: string; teamName: string; count: number }[];
    };
    captaincy: {
        mostMatchesAsCaptain: { playerId: string; playerName: string; teamName: string; matches: number }[];
        mostWinsAsCaptain: { playerId: string; playerName: string; teamName: string; wins: number }[];
        bestCaptaincyWinPct: { playerId: string; playerName: string; teamName: string; winPct: number; matches: number }[];
        mostTrophiesAsCaptain: { playerId: string; playerName: string; teamName: string; trophies: number }[];
    };
    team: {
        mostWins: { teamId: string; teamName: string; wins: number }[];
        mostTitles: { teamId: string; teamName: string; titles: number }[];
        longestWinningStreak: { teamId: string; teamName: string; streak: number }[];
        mostSuccessfulSeason: { teamId: string; teamName: string; season: number; winPct: number; points: number }[];
    };
}

export interface BatterVsBowlerRecord { batterId: string; batterName: string; bowlerId: string; bowlerName: string; runs: number; balls: number; dismissals: number; }
export interface TeamVsTeamRecord { teamAId: string; teamBId: string; teamAName: string; teamBName: string; matches: number; teamAWins: number; }
export interface PlayerVsTeamRecord { playerId: string; playerName: string; playerRole: PlayerRole; vsTeamId: string; vsTeamName: string; runs: number; balls: number; dismissals: number; wickets: number; runsConceded: number; ballsBowled: number; }
export interface PromotionRecord { season: number; promotedTeamId: string; promotedTeamName: string; relegatedTeamId: string; relegatedTeamName: string; }

export interface Sponsorship { sponsorName: string; tournamentName: string; logoColor: string; tournamentLogo?: string; tvChannel?: string; tvLogo?: string; }
export interface Brand { name: string; color: string; style: string; logo: string; }
export interface TVChannel { id: string; name: string; logo: string; color: string; minPopularity: number; tier: 'Premium' | 'Standard' | 'Budget'; }

export interface SocialMetrics {
    followers: number;
    popularity: number;
    reputation: number;
    fanHappiness: number;
    trendingScore: number;
    formRating: number;
    following?: number;
    bio?: string;
    handle?: string;
    isVerified?: boolean;
}

export interface PollOption {
    id: number;
    text: string;
    votes: number;
}

export interface SikePoll {
    id: string;
    question: string;
    options: PollOption[];
    totalVotes: number;
    userVotedOption?: number;
}

export interface PressOption {
    type: 'calm' | 'aggressive' | 'respectful' | 'ignore';
    text: string;
    label: string;
    moraleImpact: number;
    fanImpact: number;
    boardImpact: number;
}

export interface PressQuestion {
    id: string;
    journalistName: string;
    journalistHandle: string;
    journalistOutlet: string;
    question: string;
    options: PressOption[];
    answered?: boolean;
    chosenOption?: 'calm' | 'aggressive' | 'respectful' | 'ignore';
}

export interface ViralMoment {
    id: string;
    title: string;
    type: 'HAT_TRICK' | 'DOUBLE_CENTURY' | 'CENTURY' | 'FIVE_WICKET_HAUL' | 'MAN_OF_THE_MATCH' | 'LAST_BALL_SIX' | 'CONSECUTIVE_DUCKS' | 'RECORD_CHASE' | 'TROPHY_WIN';
    playerId?: string;
    playerName?: string;
    teamId?: string;
    teamName?: string;
    followersChange: number;
    matchDescription: string;
    timestamp: string;
}

export interface SikePost {
    id: string;
    authorName: string;
    authorHandle: string;
    authorAvatar?: string;
    authorRole: 'player' | 'team' | 'journalist' | 'fan' | 'news' | 'expert' | 'former_player';
    authorId?: string;
    isVerified: boolean;
    content: string;
    timestamp: string;
    likes: number;
    reposts: number;
    replies: number;
    userLiked?: boolean;
    userReposted?: boolean;
    hashtags?: string[];
    viralBadge?: string;
    poll?: SikePoll;
    pressQuestion?: PressQuestion;
    mediaImage?: string;
}

export interface SikeShareState {
    posts: SikePost[];
    playerSocials: Record<string, SocialMetrics>;
    teamSocials: Record<string, SocialMetrics>;
    followedHandles: string[];
    trendingHashtags: { tag: string; postCount: string; category: string }[];
    viralMoments: ViralMoment[];
    hallOfFameStats?: {
        totalFollowers: number;
        leagueTitles: number;
        worldCups: number;
        aiReactionsCount: number;
        mostTrendingPlayer: string;
    };
}

export interface WorldLeagueTeam {
    id: string;
    name: string; // Pure city name, e.g. "London", "Sydney", "Cape Town", "Dubai", "Karachi", "Mumbai", etc.
    origin: string; // e.g. "England", "Australia", "South Africa", "UAE", "Pakistan", "India", etc.
    logo: string;
    squad: Player[];
    isUserTeam?: boolean;
    group?: 'Group A' | 'Group B' | 'Group C' | 'Group D';
    playingXI?: string[];
    captainId?: string;
    wicketKeeperId?: string;
}

export interface WorldLeagueMatch {
    id: string;
    matchNumber: string | number;
    teamA: string;
    teamB: string;
    date: string;
    stage: 'Group Stage' | 'Quarter-Finals' | 'Semi-Finals' | 'Final';
    group?: 'Group A' | 'Group B' | 'Group C' | 'Group D';
    result?: MatchResult;
}

export interface WorldLeagueStanding {
    teamId: string;
    teamName: string;
    group: 'Group A' | 'Group B' | 'Group C' | 'Group D';
    played: number;
    won: number;
    lost: number;
    points: number;
    netRunRate: number;
    runsFor?: number;
    runsAgainst?: number;
}

export interface WorldLeagueState {
    season: number;
    status: 'ready' | 'in_progress' | 'completed';
    teams: WorldLeagueTeam[];
    matches: WorldLeagueMatch[];
    currentMatchIndex: number;
    standings: WorldLeagueStanding[];
    championTeamId?: string;
    championTeamName?: string;
    runnerUpTeamName?: string;
    mvpPlayer?: { playerId: string; playerName: string; teamName: string; statsSummary: string };
    goldenBat?: { playerId: string; playerName: string; teamName: string; runs: number; average: number; strikeRate: number };
    goldenBall?: { playerId: string; playerName: string; teamName: string; wickets: number; economy: number; bestBowling: string };
}

// Aliases for seamless backwards compatibility
export type ChampionsLeagueTeam = WorldLeagueTeam;
export type ChampionsLeagueMatch = WorldLeagueMatch;
export type ChampionsLeagueStanding = WorldLeagueStanding;
export type ChampionsLeagueState = WorldLeagueState;

export interface SeasonTransitionReport {
    season: number;
    completedAt: string;
    awards: Award;
    hallOfFame?: SeasonHallOfFame;
    teamsOfTournament?: SeasonTeamsOfTournament;
    skillProgressionSummary?: SkillProgressionSummary;
    championsLeagueWinner?: string;
    worldLeagueWinner?: string;
    retentions: {
        teamId: string;
        teamName: string;
        retained: { playerId: string; playerName: string; score: number; reason: string }[];
        released: { playerId: string; playerName: string; score: number; reason: string }[];
    }[];
    progressionHighlights: {
        playerId: string;
        playerName: string;
        teamName: string;
        ratingChange: number;
        reason: string;
    }[];
    expiredCountries: string[];
}

export interface GameData {
    userTeamId: string; teams: Team[]; grounds: Ground[]; allTeamsData: TeamData[]; allPlayers: Player[]; schedule: Record<string, Match[]>; currentMatchIndex: Record<string, number>; standings: Record<string, Standing[]>; matchResults: Record<string, MatchResult[]>; playingXIs: Record<string, Partial<Record<Format, string[]>>>; currentSeason: number; currentFormat: Format; awardsHistory: Award[]; records: { batterVsBowler: BatterVsBowlerRecord[]; teamVsTeam: TeamVsTeamRecord[]; playerVsTeam: PlayerVsTeamRecord[]; }; promotionHistory: PromotionRecord[]; popularity: number; sponsorships: Record<string, Sponsorship>; news: NewsArticle[]; activeMatch: LiveMatchState | null; scoreLimits?: Record<string, Partial<Record<Format, InningLimits>>>; availableBrands?: Brand[]; availableTVChannels?: TVChannel[]; sikeShareData?: SikeShareState;
    worldLeague?: WorldLeagueState;
    worldLeagueUserTeamName?: string | null;
    championsLeague?: WorldLeagueState;
    seasonTransitionReports?: SeasonTransitionReport[];
    hallOfFameHistory?: SeasonHallOfFame[];
    teamOfTheSeasonHistory?: Record<number, SeasonTeamsOfTournament>;
    skillProgressionHistory?: Record<number, SkillProgressionSummary>;
    transfersMadeThisSeason?: number;
    matchHistory?: MatchResult[];
    registeredMilestones?: string[];
    gameDate?: GameDate;
    seriesList?: Series[];
    scheduledEvents?: ScheduledEvent[];
    currentYearStandings?: CurrentYearStanding[];
    rankings?: {
        teams: Record<RankingFormat, TeamRanking[]>;
        players: Record<RankingFormat, FormatPlayerRankings>;
    };
    settings: {
        isDoubleRoundRobin: boolean;
    };
}

export interface DRSReviewEvent {
    id: string;
    type: 'LBW' | 'CAUGHT' | 'EDGE';
    onFieldDecision: 'OUT' | 'NOT_OUT';
    reviewingTeamId: string;
    reviewingTeamName: string;
    batterId: string;
    batterName: string;
    bowlerId: string;
    bowlerName: string;
    ballDetails: {
        runs: number;
        over: string;
        speed?: number;
    };
    ultraEdge: {
        hasEdge: boolean;
        spikeFrame: number;
    };
    ballTracking: {
        pitching: 'IN_LINE' | 'OUTSIDE_OFF' | 'OUTSIDE_LEG';
        impact: 'IN_LINE' | 'OUTSIDE_OFF';
        wickets: 'HITTING' | 'MISSING' | 'UMPIRES_CALL';
    };
    isFaultyUmpireDecision: boolean;
    finalDecision: 'OVERTURNED' | 'UPHELD' | 'UMPIRES_CALL';
    reviewResultText: string;
    wasReviewRetained: boolean;
}

export interface PendingBowlerDelivery {
    bowlerName?: string;
    speedKmh?: number;
    length: 'yorker' | 'full' | 'good' | 'short';
    line: 'off' | 'middle' | 'leg';
    speed: number;
    variation: string;
    description: string;
    recommendedShots: string[];
    riskShots: string[];
    targetX: number;
    targetY: number;
}

export interface LastShotFeedback {
    type: 'perfect_gap' | 'clean_loft' | 'boundary' | 'dot_fielded' | 'single_fielded' | 'edge_safe' | 'edge_caught' | 'play_and_miss' | 'top_edge' | 'bowled' | 'lbw';
    title: string;
    message: string;
    closestFielderName?: string;
    angleDiff?: number;
    runs: number;
    isOut: boolean;
}

export interface LiveTacticalInput {
    isBatting?: boolean;
    shotAngle?: number; // 0 - 360 degrees on field
    shotZone?: string;  // e.g. 'cover' | 'point' | 'mid_wicket' | etc.
    shotType?: string;  // e.g. 'cover_drive' | 'pull' | 'cut' | etc.
    shotCategory?: 'Attacking' | 'Defensive' | 'Lofted' | 'Placement';
    isLofted?: boolean;
    bowlingLength?: 'yorker' | 'full' | 'good' | 'short';
    bowlingLine?: 'off' | 'middle' | 'leg';
    bowlingVariation?: string;
    powerLevel?: number; // 1 to 100
    fieldPresetId?: string;
}

export interface LiveTacticalExecution {
    mode: 'batting' | 'bowling';
    shotName?: string;
    shotAngle?: number;
    shotZone?: string;
    isLofted?: boolean;
    bowlingLength?: 'yorker' | 'full' | 'good' | 'short';
    bowlingLine?: 'off' | 'middle' | 'leg';
    bowlingVariation?: string;
    runsScored: number;
    isWicket: boolean;
    quality: 'Perfect Timing' | 'Well Placed' | 'Good Connection' | 'Edged' | 'Beaten' | 'Trapped';
    summary: string;
}

export interface LiveMatchState {
    status: 'toss' | 'post_toss' | 'ready' | 'inprogress' | 'inning_break' | 'completed';
    match: Match;
    currentInningIndex: number;
    innings: Inning[];
    target: number | null;
    currentBatters: { strikerId: string; nonStrikerId: string };
    currentBowlerId: string;
    lastBallSpeed?: number;
    ballByBallId?: string;
    recentBalls: string[];
    commentary: string[]; 
    battingTeam: Team; 
    bowlingTeam: Team; 
    requiredRunRate: number; 
    currentPartnership: { runs: number, balls: number }; 
    fallOfWickets: { score: number, wicket: number, over: string, player: string }[]; 
    waitingFor: 'openers' | 'batter' | 'bowler' | 'batter_arrival' | 'bowler_change' | null; 
    strategies: { batting: Strategy; bowling: Strategy; }; 
    isExploitingWeakness?: boolean;
    autoPlayType: 'regular' | 'inning' | 'match' | null; 
    tossWinnerId: string | null; 
    tossDecision: 'bat' | 'bowl' | null;
    drsReviews?: Record<string, number>; // Remaining reviews per team ID
    pendingDrsOpportunity?: DRSReviewEvent | null;
    activeDrsModal?: DRSReviewEvent | null;
    reducedOvers?: number | null;
    milestoneEvent?: {
        title: string;
        message: string;
        type: 'batting' | 'bowling' | 'career' | 'leader' | 'match_winner';
        playerId: string;
    } | null;
    lastTacticalExecution?: LiveTacticalExecution | null;
    pendingBowlerDelivery?: PendingBowlerDelivery | null;
    lastShotFeedback?: LastShotFeedback | null;
}

export interface Message { id: string; text: string; sender: 'user' | 'model' | 'bot'; timestamp?: Date; }
