import { RawPlayerData } from '../types';

// Part 1: West Indies, Sri Lanka, South Africa, England, Australia, New Zealand
export const RAW_INTERNATIONAL_PART1: RawPlayerData[] = [
    // 🇯🇲 WEST INDIES (New Additions)
    { id: 'int-wi-4', name: 'R. Lewis', age: 26, nationality: 'West Indies', role: 'BT', batting: 69, bowling: 20, style: 'A', isForeign: true },
    { id: 'int-wi-5', name: 'C. Holder', age: 31, nationality: 'West Indies', role: 'AR', batting: 69, bowling: 65, style: 'NA', isForeign: true, traits: ['mv'] },
    { id: 'int-wi-6', name: 'D. Kingman', age: 27, nationality: 'West Indies', role: 'BT', batting: 69, bowling: 18, style: 'A', isForeign: true },
    { id: 'int-wi-7', name: 'S. Powell', age: 25, nationality: 'West Indies', role: 'BT', batting: 68, bowling: 15, style: 'N', isForeign: true },
    { id: 'int-wi-8', name: 'M. Grant', age: 28, nationality: 'West Indies', role: 'AR', batting: 65, bowling: 60, style: 'N', isForeign: true, traits: ['m'] },
    { id: 'int-wi-9', name: 'T. Edwards', age: 24, nationality: 'West Indies', role: 'SB', batting: 40, bowling: 67, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-wi-10', name: 'K. Brooks', age: 29, nationality: 'West Indies', role: 'BL', batting: 28, bowling: 69, style: 'D', isForeign: true, traits: ['fb'] },
    { id: 'int-wi-11', name: 'J. Allen', age: 23, nationality: 'West Indies', role: 'BL', batting: 26, bowling: 68, style: 'N', isForeign: true, traits: ['fbs'] },
    { id: 'int-wi-12', name: 'R. Baptiste', age: 27, nationality: 'West Indies', role: 'AR', batting: 63, bowling: 62, style: 'NA', isForeign: true, traits: ['lac'] },
    { id: 'int-wi-13', name: 'A. Sinclair', age: 24, nationality: 'West Indies', role: 'BT', batting: 66, bowling: 22, style: 'N', isForeign: true },
    { id: 'int-wi-14', name: 'L. Thomas', age: 26, nationality: 'West Indies', role: 'WK', batting: 60, bowling: 68, style: 'N', isForeign: true },
    { id: 'int-wi-15', name: 'P. Johnson', age: 25, nationality: 'West Indies', role: 'BL', batting: 24, bowling: 69, style: 'D', isForeign: true, traits: ['fb'] },

    // 🇱🇰 SRI LANKA (New Additions)
    { id: 'int-sl-3', name: 'R. Jayalath', age: 27, nationality: 'Sri Lanka', role: 'BT', batting: 69, bowling: 12, style: 'N', isForeign: true, pos: 'OP' },
    { id: 'int-sl-4', name: 'K. Perera', age: 30, nationality: 'Sri Lanka', role: 'BT', batting: 69, bowling: 18, style: 'A', isForeign: true, pos: 'OP' },
    { id: 'int-sl-5', name: 'S. Fernando', age: 26, nationality: 'Sri Lanka', role: 'BT', batting: 69, bowling: 15, style: 'N', isForeign: true },
    { id: 'int-sl-6', name: 'N. Silva', age: 28, nationality: 'Sri Lanka', role: 'BT', batting: 68, bowling: 10, style: 'D', isForeign: true },
    { id: 'int-sl-7', name: 'A. Wickram', age: 24, nationality: 'Sri Lanka', role: 'BT', batting: 66, bowling: 8, style: 'N', isForeign: true },
    { id: 'int-sl-8', name: 'M. Gunasekara', age: 28, nationality: 'Sri Lanka', role: 'WK', batting: 65, bowling: 69, style: 'N', isForeign: true },
    { id: 'int-sl-9', name: 'D. Samar', age: 29, nationality: 'Sri Lanka', role: 'WK', batting: 69, bowling: 69, style: 'A', isForeign: true },
    { id: 'int-sl-10', name: 'L. Karunaratne', age: 25, nationality: 'Sri Lanka', role: 'WK', batting: 60, bowling: 68, style: 'D', isForeign: true },
    { id: 'int-sl-11', name: 'H. Rajapaksa', age: 31, nationality: 'Sri Lanka', role: 'AR', batting: 68, bowling: 62, style: 'NA', isForeign: true, traits: ['laos'] },
    { id: 'int-sl-12', name: 'P. Mathews', age: 33, nationality: 'Sri Lanka', role: 'AR', batting: 65, bowling: 60, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-sl-13', name: 'T. Mendis', age: 25, nationality: 'Sri Lanka', role: 'AR', batting: 60, bowling: 58, style: 'N', isForeign: true, traits: ['os'] },
    { id: 'int-sl-14', name: 'S. Kulasekara', age: 27, nationality: 'Sri Lanka', role: 'AR', batting: 58, bowling: 64, style: 'D', isForeign: true, traits: ['mv'] },
    { id: 'int-sl-15', name: 'R. Jayasinghe', age: 28, nationality: 'Sri Lanka', role: 'SB', batting: 40, bowling: 69, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-sl-16', name: 'M. Dananjaya', age: 26, nationality: 'Sri Lanka', role: 'SB', batting: 38, bowling: 69, style: 'N', isForeign: true, traits: ['ls'] },
    { id: 'int-sl-17', name: 'K. Silva', age: 24, nationality: 'Sri Lanka', role: 'SB', batting: 42, bowling: 68, style: 'N', isForeign: true, traits: ['laos'] },
    { id: 'int-sl-18', name: 'A. Herath', age: 32, nationality: 'Sri Lanka', role: 'SB', batting: 35, bowling: 69, style: 'D', isForeign: true, traits: ['laos'] },
    { id: 'int-sl-19', name: 'L. Kumara', age: 27, nationality: 'Sri Lanka', role: 'BL', batting: 28, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-sl-20', name: 'S. Madushan', age: 25, nationality: 'Sri Lanka', role: 'BL', batting: 26, bowling: 69, style: 'D', isForeign: true, traits: ['fbs'] },
    { id: 'int-sl-21', name: 'N. Pradeep', age: 31, nationality: 'Sri Lanka', role: 'BL', batting: 24, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-sl-22', name: 'C. Lakmal', age: 32, nationality: 'Sri Lanka', role: 'BL', batting: 25, bowling: 69, style: 'D', isForeign: true, traits: ['mv'] },
    { id: 'int-sl-23', name: 'R. Pathirana', age: 22, nationality: 'Sri Lanka', role: 'BL', batting: 22, bowling: 69, style: 'A', isForeign: true, traits: ['fbs'] },
    { id: 'int-sl-24', name: 'M. Fernando', age: 29, nationality: 'Sri Lanka', role: 'BL', batting: 30, bowling: 68, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-sl-25', name: 'I. Peris', age: 23, nationality: 'Sri Lanka', role: 'BT', batting: 62, bowling: 18, style: 'N', isForeign: true },
    { id: 'int-sl-26', name: 'D. Alwis', age: 26, nationality: 'Sri Lanka', role: 'AR', batting: 57, bowling: 55, style: 'NA', isForeign: true, traits: ['os'] },
    { id: 'int-sl-27', name: 'S. Nissanka', age: 24, nationality: 'Sri Lanka', role: 'BT', batting: 64, bowling: 12, style: 'A', isForeign: true },
    { id: 'int-sl-28', name: 'T. Bandara', age: 25, nationality: 'Sri Lanka', role: 'SB', batting: 36, bowling: 65, style: 'D', isForeign: true, traits: ['ls'] },

    // 🇿🇦 SOUTH AFRICA (New Additions)
    { id: 'int-sa-3', name: 'Q. van Rooyen', age: 29, nationality: 'South Africa', role: 'BT', batting: 69, bowling: 22, style: 'A', isForeign: true, pos: 'OP' },
    { id: 'int-sa-4', name: 'L. Pretorius', age: 27, nationality: 'South Africa', role: 'BT', batting: 69, bowling: 18, style: 'N', isForeign: true, pos: 'OP' },
    { id: 'int-sa-5', name: 'T. Mbeki', age: 26, nationality: 'South Africa', role: 'BT', batting: 69, bowling: 15, style: 'D', isForeign: true },
    { id: 'int-sa-6', name: 'R. Malan', age: 28, nationality: 'South Africa', role: 'BT', batting: 69, bowling: 12, style: 'N', isForeign: true },
    { id: 'int-sa-7', name: 'S. de Kockton', age: 25, nationality: 'South Africa', role: 'BT', batting: 68, bowling: 10, style: 'A', isForeign: true },
    { id: 'int-sa-8', name: 'J. Kruger', age: 30, nationality: 'South Africa', role: 'WK', batting: 69, bowling: 69, style: 'NA', isForeign: true },
    { id: 'int-sa-9', name: 'B. van Dyk', age: 26, nationality: 'South Africa', role: 'WK', batting: 65, bowling: 69, style: 'D', isForeign: true },
    { id: 'int-sa-10', name: 'A. Moller', age: 24, nationality: 'South Africa', role: 'WK', batting: 60, bowling: 68, style: 'N', isForeign: true },
    { id: 'int-sa-11', name: 'H. du Pless', age: 33, nationality: 'South Africa', role: 'AR', batting: 68, bowling: 62, style: 'NA', isForeign: true, traits: ['os'] },
    { id: 'int-sa-12', name: 'S. Ngidi', age: 27, nationality: 'South Africa', role: 'AR', batting: 55, bowling: 65, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-sa-13', name: 'K. Rabada', age: 28, nationality: 'South Africa', role: 'AR', batting: 58, bowling: 69, style: 'A', isForeign: true, traits: ['fbs'] },
    { id: 'int-sa-14', name: 'T. Maharaj', age: 31, nationality: 'South Africa', role: 'SB', batting: 42, bowling: 69, style: 'D', isForeign: true, traits: ['laos'] },
    { id: 'int-sa-15', name: 'L. Shamsi', age: 30, nationality: 'South Africa', role: 'SB', batting: 38, bowling: 69, style: 'N', isForeign: true, traits: ['lac'] },
    { id: 'int-sa-16', name: 'A. Botha', age: 26, nationality: 'South Africa', role: 'SB', batting: 40, bowling: 68, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-sa-17', name: 'J. Nortje', age: 29, nationality: 'South Africa', role: 'BL', batting: 28, bowling: 69, style: 'A', isForeign: true, traits: ['fbs'] },
    { id: 'int-sa-18', name: 'K. Steynson', age: 31, nationality: 'South Africa', role: 'BL', batting: 26, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-sa-19', name: 'P. Coetzee', age: 23, nationality: 'South Africa', role: 'BL', batting: 24, bowling: 69, style: 'D', isForeign: true, traits: ['fb'] },
    { id: 'int-sa-20', name: 'M. Jansen', age: 24, nationality: 'South Africa', role: 'BL', batting: 30, bowling: 69, style: 'N', isForeign: true, traits: ['laos'] },
    { id: 'int-sa-21', name: 'R. Olivier', age: 30, nationality: 'South Africa', role: 'BL', batting: 22, bowling: 69, style: 'D', isForeign: true, traits: ['fb'] },
    { id: 'int-sa-22', name: 'S. Maphosa', age: 26, nationality: 'South Africa', role: 'BL', batting: 25, bowling: 69, style: 'N', isForeign: true, traits: ['fbs'] },
    { id: 'int-sa-23', name: 'E. Lutho', age: 24, nationality: 'South Africa', role: 'BL', batting: 27, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-sa-24', name: 'D. Klaasen', age: 28, nationality: 'South Africa', role: 'BT', batting: 66, bowling: 15, style: 'A', isForeign: true },
    { id: 'int-sa-25', name: 'P. Adams', age: 26, nationality: 'South Africa', role: 'AR', batting: 60, bowling: 58, style: 'NA', isForeign: true, traits: ['lac'] },
    { id: 'int-sa-26', name: 'Z. Maseko', age: 23, nationality: 'South Africa', role: 'SB', batting: 35, bowling: 65, style: 'D', isForeign: true, traits: ['ls'] },
    { id: 'int-sa-27', name: 'W. Nel', age: 27, nationality: 'South Africa', role: 'BL', batting: 23, bowling: 69, style: 'N', isForeign: true, traits: ['mv'] },

    // 🏴 ENGLAND (New Additions)
    { id: 'int-en-3', name: 'R. Haleson', age: 32, nationality: 'England', role: 'BT', batting: 69, bowling: 18, style: 'A', isForeign: true, pos: 'OP' },
    { id: 'int-en-4', name: 'T. Crawleyton', age: 26, nationality: 'England', role: 'BT', batting: 69, bowling: 15, style: 'N', isForeign: true, pos: 'OP' },
    { id: 'int-en-5', name: 'J. Rootman', age: 33, nationality: 'England', role: 'BT', batting: 69, bowling: 25, style: 'NA', isForeign: true, traits: ['os'] },
    { id: 'int-en-6', name: 'B. Stokesley', age: 32, nationality: 'England', role: 'BT', batting: 69, bowling: 35, style: 'A', isForeign: true, traits: ['fb'] },
    { id: 'int-en-7', name: 'O. Popeham', age: 26, nationality: 'England', role: 'BT', batting: 69, bowling: 12, style: 'N', isForeign: true },
    { id: 'int-en-8', name: 'J. Butleron', age: 33, nationality: 'England', role: 'WK', batting: 69, bowling: 69, style: 'A', isForeign: true },
    { id: 'int-en-9', name: 'S. Foakesby', age: 30, nationality: 'England', role: 'WK', batting: 65, bowling: 69, style: 'D', isForeign: true },
    { id: 'int-en-10', name: 'T. Bairston', age: 33, nationality: 'England', role: 'WK', batting: 68, bowling: 69, style: 'NA', isForeign: true },
    { id: 'int-en-11', name: 'L. Woakeson', age: 32, nationality: 'England', role: 'AR', batting: 60, bowling: 65, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-en-12', name: 'M. Aliyah', age: 34, nationality: 'England', role: 'AR', batting: 58, bowling: 68, style: 'NA', isForeign: true, traits: ['os'] },
    { id: 'int-en-13', name: 'S. Curranley', age: 25, nationality: 'England', role: 'AR', batting: 62, bowling: 66, style: 'A', isForeign: true, traits: ['laos'] },
    { id: 'int-en-14', name: 'A. Rashidon', age: 34, nationality: 'England', role: 'SB', batting: 40, bowling: 69, style: 'N', isForeign: true, traits: ['ls'] },
    { id: 'int-en-15', name: 'J. Leachman', age: 31, nationality: 'England', role: 'SB', batting: 38, bowling: 69, style: 'D', isForeign: true, traits: ['laos'] },
    { id: 'int-en-16', name: 'R. Besset', age: 26, nationality: 'England', role: 'SB', batting: 36, bowling: 68, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-en-17', name: 'J. Andersonic', age: 38, nationality: 'England', role: 'BL', batting: 24, bowling: 69, style: 'D', isForeign: true, traits: ['mv'] },
    { id: 'int-en-18', name: 'S. Broadley', age: 36, nationality: 'England', role: 'BL', batting: 26, bowling: 69, style: 'N', isForeign: true, traits: ['fbs'] },
    { id: 'int-en-19', name: 'M. Woodson', age: 32, nationality: 'England', role: 'BL', batting: 28, bowling: 69, style: 'A', isForeign: true, traits: ['fbs'] },
    { id: 'int-en-20', name: 'O. Stoneham', age: 29, nationality: 'England', role: 'BL', batting: 25, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-en-21', name: 'C. Archeron', age: 29, nationality: 'England', role: 'BL', batting: 30, bowling: 69, style: 'A', isForeign: true, traits: ['fbs'] },
    { id: 'int-en-22', name: 'D. Willeyson', age: 33, nationality: 'England', role: 'BL', batting: 32, bowling: 69, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-en-23', name: 'P. Overtonic', age: 29, nationality: 'England', role: 'BL', batting: 27, bowling: 69, style: 'D', isForeign: true, traits: ['fb'] },
    { id: 'int-en-24', name: 'H. Brookton', age: 25, nationality: 'England', role: 'BT', batting: 68, bowling: 18, style: 'A', isForeign: true },
    { id: 'int-en-25', name: 'J. Vinceley', age: 31, nationality: 'England', role: 'BT', batting: 66, bowling: 15, style: 'N', isForeign: true },
    { id: 'int-en-26', name: 'C. Jordanic', age: 33, nationality: 'England', role: 'BL', batting: 29, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },

    // 🇦🇺 AUSTRALIA (New Additions)
    { id: 'int-au-11', name: 'K. Rowden', age: 26, nationality: 'Australia', role: 'BT', batting: 69, bowling: 12, style: 'N', isForeign: true },
    { id: 'int-au-12', name: 'D. Fraser', age: 24, nationality: 'Australia', role: 'BT', batting: 68, bowling: 18, style: 'D', isForeign: true },
    { id: 'int-au-13', name: 'T. O’Neil', age: 25, nationality: 'Australia', role: 'BT', batting: 66, bowling: 10, style: 'A', isForeign: true },
    { id: 'int-au-14', name: 'S. Molnar', age: 28, nationality: 'Australia', role: 'WK', batting: 65, bowling: 69, style: 'A', isForeign: true },
    { id: 'int-au-15', name: 'R. Hughes', age: 27, nationality: 'Australia', role: 'WK', batting: 62, bowling: 68, style: 'D', isForeign: true },
    { id: 'int-au-16', name: 'P. Connell', age: 26, nationality: 'Australia', role: 'AR', batting: 60, bowling: 58, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-au-17', name: 'R. Steele', age: 29, nationality: 'Australia', role: 'AR', batting: 63, bowling: 61, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-au-18', name: 'N. Clarke', age: 24, nationality: 'Australia', role: 'SB', batting: 44, bowling: 68, style: 'N', isForeign: true, traits: ['ls'] },
    { id: 'int-au-19', name: 'L. Sandhu', age: 27, nationality: 'Australia', role: 'SB', batting: 40, bowling: 69, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-au-20', name: 'J. Morris', age: 25, nationality: 'Australia', role: 'SB', batting: 38, bowling: 66, style: 'N', isForeign: true, traits: ['laos'] },
    { id: 'int-au-21', name: 'S. Cartwright', age: 29, nationality: 'Australia', role: 'BL', batting: 30, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-au-22', name: 'M. Doyle', age: 28, nationality: 'Australia', role: 'BL', batting: 28, bowling: 66, style: 'D', isForeign: true, traits: ['fbs'] },
    { id: 'int-au-23', name: 'H. Price', age: 26, nationality: 'Australia', role: 'BL', batting: 35, bowling: 65, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-au-24', name: 'E. Norton', age: 25, nationality: 'Australia', role: 'BL', batting: 26, bowling: 67, style: 'D', isForeign: true, traits: ['fb'] },
    { id: 'int-au-25', name: 'T. Walsh', age: 24, nationality: 'Australia', role: 'BL', batting: 29, bowling: 64, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-au-26', name: 'J. Keaton', age: 27, nationality: 'Australia', role: 'BL', batting: 31, bowling: 63, style: 'N', isForeign: true, traits: ['fbs'] },
    { id: 'int-au-27', name: 'R. Bowen', age: 23, nationality: 'Australia', role: 'BL', batting: 24, bowling: 62, style: 'D', isForeign: true, traits: ['fb'] },
    { id: 'int-au-28', name: 'C. Voss', age: 26, nationality: 'Australia', role: 'AR', batting: 58, bowling: 55, style: 'NA', isForeign: true, traits: ['m'] },
    { id: 'int-au-29', name: 'B. Langford', age: 24, nationality: 'Australia', role: 'BT', batting: 64, bowling: 20, style: 'N', isForeign: true },

    // 🇳🇿 NEW ZEALAND (New Additions)
    { id: 'int-nz-6', name: 'T. McAllum', age: 28, nationality: 'New Zealand', role: 'BT', batting: 69, bowling: 15, style: 'N', isForeign: true },
    { id: 'int-nz-7', name: 'J. Rutter', age: 26, nationality: 'New Zealand', role: 'BT', batting: 69, bowling: 18, style: 'D', isForeign: true },
    { id: 'int-nz-8', name: 'P. Elson', age: 25, nationality: 'New Zealand', role: 'BT', batting: 68, bowling: 20, style: 'N', isForeign: true },
    { id: 'int-nz-9', name: 'M. Calder', age: 29, nationality: 'New Zealand', role: 'WK', batting: 65, bowling: 69, style: 'N', isForeign: true },
    { id: 'int-nz-10', name: 'J. Moana', age: 27, nationality: 'New Zealand', role: 'AR', batting: 60, bowling: 58, style: 'NA', isForeign: true, traits: ['mv'] },
    { id: 'int-nz-11', name: 'R. Teague', age: 26, nationality: 'New Zealand', role: 'AR', batting: 63, bowling: 61, style: 'N', isForeign: true, traits: ['os'] },
    { id: 'int-nz-12', name: 'L. Faulkner', age: 28, nationality: 'New Zealand', role: 'AR', batting: 58, bowling: 62, style: 'D', isForeign: true, traits: ['fb'] },
    { id: 'int-nz-13', name: 'K. Patel', age: 25, nationality: 'New Zealand', role: 'SB', batting: 42, bowling: 67, style: 'D', isForeign: true, traits: ['ls'] },
    { id: 'int-nz-14', name: 'N. Rawiri', age: 24, nationality: 'New Zealand', role: 'SB', batting: 40, bowling: 65, style: 'N', isForeign: true, traits: ['laos'] },
    { id: 'int-nz-15', name: 'A. Singh', age: 26, nationality: 'New Zealand', role: 'SB', batting: 38, bowling: 64, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-nz-16', name: 'H. McKay', age: 28, nationality: 'New Zealand', role: 'BL', batting: 28, bowling: 69, style: 'D', isForeign: true, traits: ['fb'] },
    { id: 'int-nz-17', name: 'T. Ransom', age: 27, nationality: 'New Zealand', role: 'BL', batting: 30, bowling: 68, style: 'N', isForeign: true, traits: ['fbs'] },
    { id: 'int-nz-18', name: 'O. Bennett', age: 25, nationality: 'New Zealand', role: 'BL', batting: 26, bowling: 66, style: 'D', isForeign: true, traits: ['mv'] },
    { id: 'int-nz-19', name: 'J. Whittaker', age: 24, nationality: 'New Zealand', role: 'BL', batting: 29, bowling: 65, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-nz-20', name: 'E. Foster', age: 26, nationality: 'New Zealand', role: 'BL', batting: 27, bowling: 64, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-nz-21', name: 'R. Collins', age: 23, nationality: 'New Zealand', role: 'BL', batting: 24, bowling: 63, style: 'D', isForeign: true, traits: ['fb'] },
    { id: 'int-nz-22', name: 'D. Lawson', age: 25, nationality: 'New Zealand', role: 'BT', batting: 66, bowling: 22, style: 'N', isForeign: true },
    { id: 'int-nz-23', name: 'S. Grant', age: 26, nationality: 'New Zealand', role: 'AR', batting: 59, bowling: 55, style: 'NA', isForeign: true, traits: ['os'] },
];

// Part 2: India, Netherlands, Scotland, USA, Nepal, Namibia, Oman, Canada, UAE, Bangladesh, Afghanistan, Ireland, Zimbabwe
export const RAW_INTERNATIONAL_PART2: RawPlayerData[] = [
    // 🇮🇳 INDIA (20 Players)
    { id: 'int-ind-1', name: 'Arjun Malhotra', age: 26, nationality: 'India', role: 'BT', batting: 69, bowling: 20, style: 'A', isForeign: true, pos: 'OP' },
    { id: 'int-ind-2', name: 'Rohit Sen', age: 28, nationality: 'India', role: 'BT', batting: 69, bowling: 18, style: 'N', isForeign: true, pos: 'OP' },
    { id: 'int-ind-3', name: 'Kunal Verma', age: 25, nationality: 'India', role: 'BT', batting: 69, bowling: 15, style: 'N', isForeign: true },
    { id: 'int-ind-4', name: 'Devansh Iyer', age: 27, nationality: 'India', role: 'BT', batting: 69, bowling: 25, style: 'NA', isForeign: true },
    { id: 'int-ind-5', name: 'Samar Kulkarni', age: 29, nationality: 'India', role: 'BT', batting: 69, bowling: 18, style: 'D', isForeign: true },
    { id: 'int-ind-6', name: 'Ishaan Rao', age: 26, nationality: 'India', role: 'WK', batting: 69, bowling: 69, style: 'A', isForeign: true },
    { id: 'int-ind-7', name: 'Nikhil Patil', age: 24, nationality: 'India', role: 'WK', batting: 65, bowling: 69, style: 'D', isForeign: true },
    { id: 'int-ind-8', name: 'Aarav Mehta', age: 28, nationality: 'India', role: 'AR', batting: 68, bowling: 62, style: 'NA', isForeign: true, traits: ['ls'] },
    { id: 'int-ind-9', name: 'Rajat Choudhary', age: 27, nationality: 'India', role: 'AR', batting: 65, bowling: 64, style: 'N', isForeign: true, traits: ['os'] },
    { id: 'int-ind-10', name: 'Manav Singh', age: 25, nationality: 'India', role: 'AR', batting: 60, bowling: 58, style: 'D', isForeign: true, traits: ['mv'] },
    { id: 'int-ind-11', name: 'Yash Tripathi', age: 26, nationality: 'India', role: 'SB', batting: 42, bowling: 69, style: 'N', isForeign: true, traits: ['ls'] },
    { id: 'int-ind-12', name: 'Pankaj Mishra', age: 29, nationality: 'India', role: 'SB', batting: 38, bowling: 69, style: 'D', isForeign: true, traits: ['laos'] },
    { id: 'int-ind-13', name: 'Suresh Nayak', age: 28, nationality: 'India', role: 'BL', batting: 30, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-ind-14', name: 'Akash Thakur', age: 27, nationality: 'India', role: 'BL', batting: 28, bowling: 69, style: 'A', isForeign: true, traits: ['fbs'] },
    { id: 'int-ind-15', name: 'Vikram Deshpande', age: 25, nationality: 'India', role: 'BL', batting: 26, bowling: 69, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-ind-16', name: 'Harsh Bansal', age: 24, nationality: 'India', role: 'BL', batting: 24, bowling: 69, style: 'D', isForeign: true, traits: ['fb'] },
    { id: 'int-ind-17', name: 'Pranav Joshi', age: 23, nationality: 'India', role: 'BT', batting: 66, bowling: 20, style: 'N', isForeign: true },
    { id: 'int-ind-18', name: 'Rishi Malviya', age: 25, nationality: 'India', role: 'AR', batting: 58, bowling: 60, style: 'N', isForeign: true, traits: ['lac'] },
    { id: 'int-ind-19', name: 'Deepak Solanki', age: 26, nationality: 'India', role: 'SB', batting: 40, bowling: 68, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-ind-20', name: 'Mohit Kapoor', age: 24, nationality: 'India', role: 'BL', batting: 25, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },

    // 🇳🇱 NETHERLANDS (15 Players)
    { id: 'int-ned-1', name: 'Jeroen Van Dijk', age: 27, nationality: 'Netherlands', role: 'BT', batting: 68, bowling: 18, style: 'N', isForeign: true, pos: 'OP' },
    { id: 'int-ned-2', name: 'Mark De Vries', age: 29, nationality: 'Netherlands', role: 'BT', batting: 65, bowling: 20, style: 'A', isForeign: true, pos: 'OP' },
    { id: 'int-ned-3', name: 'Tim Verhoeven', age: 26, nationality: 'Netherlands', role: 'BT', batting: 66, bowling: 22, style: 'N', isForeign: true },
    { id: 'int-ned-4', name: 'Lucas Meijer', age: 25, nationality: 'Netherlands', role: 'BT', batting: 64, bowling: 18, style: 'D', isForeign: true },
    { id: 'int-ned-5', name: 'Bram Jansen', age: 28, nationality: 'Netherlands', role: 'WK', batting: 63, bowling: 69, style: 'N', isForeign: true },
    { id: 'int-ned-6', name: 'Pieter Kok', age: 26, nationality: 'Netherlands', role: 'WK', batting: 60, bowling: 68, style: 'D', isForeign: true },
    { id: 'int-ned-7', name: 'Wout Bakker', age: 27, nationality: 'Netherlands', role: 'AR', batting: 60, bowling: 62, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-ned-8', name: 'Stefan Mulder', age: 28, nationality: 'Netherlands', role: 'AR', batting: 58, bowling: 60, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-ned-9', name: 'Rik Smit', age: 26, nationality: 'Netherlands', role: 'SB', batting: 40, bowling: 69, style: 'N', isForeign: true, traits: ['ls'] },
    { id: 'int-ned-10', name: 'Koen Bos', age: 24, nationality: 'Netherlands', role: 'SB', batting: 38, bowling: 68, style: 'D', isForeign: true, traits: ['laos'] },
    { id: 'int-ned-11', name: 'Niels Van Rijn', age: 28, nationality: 'Netherlands', role: 'BL', batting: 28, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-ned-12', name: 'Daan Hofman', age: 26, nationality: 'Netherlands', role: 'BL', batting: 26, bowling: 69, style: 'D', isForeign: true, traits: ['mv'] },
    { id: 'int-ned-13', name: 'Arjen Post', age: 25, nationality: 'Netherlands', role: 'BL', batting: 25, bowling: 69, style: 'N', isForeign: true, traits: ['fbs'] },
    { id: 'int-ned-14', name: 'Tom Kuipers', age: 24, nationality: 'Netherlands', role: 'BT', batting: 62, bowling: 18, style: 'N', isForeign: true },
    { id: 'int-ned-15', name: 'Hugo Van Leeuwen', age: 25, nationality: 'Netherlands', role: 'AR', batting: 55, bowling: 58, style: 'N', isForeign: true, traits: ['lac'] },

    // 🏴 SCOTLAND (15 Players)
    { id: 'int-sco-1', name: 'Callum Fraser', age: 28, nationality: 'Scotland', role: 'BT', batting: 68, bowling: 20, style: 'N', isForeign: true, pos: 'OP' },
    { id: 'int-sco-2', name: 'Ryan McLeod', age: 26, nationality: 'Scotland', role: 'BT', batting: 66, bowling: 18, style: 'A', isForeign: true, pos: 'OP' },
    { id: 'int-sco-3', name: 'Euan Campbell', age: 25, nationality: 'Scotland', role: 'BT', batting: 65, bowling: 22, style: 'N', isForeign: true },
    { id: 'int-sco-4', name: 'Finlay Ross', age: 27, nationality: 'Scotland', role: 'BT', batting: 64, bowling: 18, style: 'D', isForeign: true },
    { id: 'int-sco-5', name: 'Alistair Grant', age: 29, nationality: 'Scotland', role: 'WK', batting: 64, bowling: 69, style: 'N', isForeign: true },
    { id: 'int-sco-6', name: 'Duncan Kerr', age: 26, nationality: 'Scotland', role: 'WK', batting: 60, bowling: 68, style: 'D', isForeign: true },
    { id: 'int-sco-7', name: 'Jamie Douglas', age: 28, nationality: 'Scotland', role: 'AR', batting: 60, bowling: 62, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-sco-8', name: 'Scott Murray', age: 27, nationality: 'Scotland', role: 'AR', batting: 58, bowling: 60, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-sco-9', name: 'Liam Boyd', age: 25, nationality: 'Scotland', role: 'SB', batting: 40, bowling: 69, style: 'N', isForeign: true, traits: ['ls'] },
    { id: 'int-sco-10', name: 'Angus Reid', age: 24, nationality: 'Scotland', role: 'SB', batting: 38, bowling: 68, style: 'D', isForeign: true, traits: ['laos'] },
    { id: 'int-sco-11', name: 'Nathan Wallace', age: 28, nationality: 'Scotland', role: 'BL', batting: 28, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-sco-12', name: 'Craig Thomson', age: 26, nationality: 'Scotland', role: 'BL', batting: 26, bowling: 69, style: 'D', isForeign: true, traits: ['fbs'] },
    { id: 'int-sco-13', name: 'Ross Hamilton', age: 25, nationality: 'Scotland', role: 'BL', batting: 25, bowling: 69, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-sco-14', name: 'Ben Sinclair', age: 23, nationality: 'Scotland', role: 'BT', batting: 62, bowling: 18, style: 'N', isForeign: true },
    { id: 'int-sco-15', name: 'Oliver Paterson', age: 25, nationality: 'Scotland', role: 'AR', batting: 55, bowling: 58, style: 'N', isForeign: true, traits: ['m'] },

    // 🇺🇸 USA (15 Players)
    { id: 'int-usa-1', name: 'Aaron Mitchell', age: 27, nationality: 'USA', role: 'BT', batting: 68, bowling: 20, style: 'A', isForeign: true, pos: 'OP' },
    { id: 'int-usa-2', name: 'Jason Miller', age: 28, nationality: 'USA', role: 'BT', batting: 66, bowling: 18, style: 'N', isForeign: true, pos: 'OP' },
    { id: 'int-usa-3', name: 'Chris Walker', age: 26, nationality: 'USA', role: 'BT', batting: 65, bowling: 22, style: 'N', isForeign: true },
    { id: 'int-usa-4', name: 'Ryan Coleman', age: 25, nationality: 'USA', role: 'BT', batting: 64, bowling: 18, style: 'D', isForeign: true },
    { id: 'int-usa-5', name: 'David Brooks', age: 29, nationality: 'USA', role: 'WK', batting: 64, bowling: 69, style: 'N', isForeign: true },
    { id: 'int-usa-6', name: 'Ethan Rogers', age: 24, nationality: 'USA', role: 'WK', batting: 60, bowling: 68, style: 'D', isForeign: true },
    { id: 'int-usa-7', name: 'Michael Turner', age: 28, nationality: 'USA', role: 'AR', batting: 60, bowling: 62, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-usa-8', name: 'Luke Anderson', age: 27, nationality: 'USA', role: 'AR', batting: 58, bowling: 60, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-usa-9', name: 'Sahil Patel', age: 26, nationality: 'USA', role: 'SB', batting: 40, bowling: 69, style: 'N', isForeign: true, traits: ['ls'] },
    { id: 'int-usa-10', name: 'Rohan Shah', age: 24, nationality: 'USA', role: 'SB', batting: 38, bowling: 68, style: 'D', isForeign: true, traits: ['laos'] },
    { id: 'int-usa-11', name: 'Brandon Lewis', age: 28, nationality: 'USA', role: 'BL', batting: 28, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-usa-12', name: 'Tyler Moore', age: 26, nationality: 'USA', role: 'BL', batting: 26, bowling: 69, style: 'D', isForeign: true, traits: ['fbs'] },
    { id: 'int-usa-13', name: 'Nathan Scott', age: 25, nationality: 'USA', role: 'BL', batting: 25, bowling: 69, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-usa-14', name: 'Kevin Young', age: 24, nationality: 'USA', role: 'BT', batting: 62, bowling: 18, style: 'N', isForeign: true },
    { id: 'int-usa-15', name: 'Daniel Price', age: 25, nationality: 'USA', role: 'AR', batting: 55, bowling: 58, style: 'N', isForeign: true, traits: ['fb'] },

    // 🇳🇵 NEPAL (15 Players)
    { id: 'int-nep-1', name: 'Aashish Karki', age: 26, nationality: 'Nepal', role: 'BT', batting: 66, bowling: 18, style: 'A', isForeign: true, pos: 'OP' },
    { id: 'int-nep-2', name: 'Rajan Thapa', age: 27, nationality: 'Nepal', role: 'BT', batting: 64, bowling: 20, style: 'N', isForeign: true, pos: 'OP' },
    { id: 'int-nep-3', name: 'Suman Bista', age: 25, nationality: 'Nepal', role: 'BT', batting: 65, bowling: 22, style: 'N', isForeign: true },
    { id: 'int-nep-4', name: 'Dipesh Rana', age: 24, nationality: 'Nepal', role: 'BT', batting: 62, bowling: 18, style: 'D', isForeign: true },
    { id: 'int-nep-5', name: 'Anil Khadka', age: 28, nationality: 'Nepal', role: 'WK', batting: 63, bowling: 69, style: 'N', isForeign: true },
    { id: 'int-nep-6', name: 'Roshan Gurung', age: 25, nationality: 'Nepal', role: 'WK', batting: 60, bowling: 68, style: 'D', isForeign: true },
    { id: 'int-nep-7', name: 'Kiran Shrestha', age: 27, nationality: 'Nepal', role: 'AR', batting: 58, bowling: 60, style: 'N', isForeign: true, traits: ['os'] },
    { id: 'int-nep-8', name: 'Bibek Adhikari', age: 26, nationality: 'Nepal', role: 'AR', batting: 56, bowling: 58, style: 'D', isForeign: true, traits: ['mv'] },
    { id: 'int-nep-9', name: 'Sagar Lamichhane', age: 25, nationality: 'Nepal', role: 'SB', batting: 42, bowling: 69, style: 'N', isForeign: true, traits: ['ls'] },
    { id: 'int-nep-10', name: 'Prakash Poudel', age: 24, nationality: 'Nepal', role: 'SB', batting: 38, bowling: 68, style: 'D', isForeign: true, traits: ['laos'] },
    { id: 'int-nep-11', name: 'Nischal Bohara', age: 28, nationality: 'Nepal', role: 'BL', batting: 28, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-nep-12', name: 'Ujjwal Basnet', age: 26, nationality: 'Nepal', role: 'BL', batting: 26, bowling: 69, style: 'D', isForeign: true, traits: ['mv'] },
    { id: 'int-nep-13', name: 'Ritesh Koirala', age: 25, nationality: 'Nepal', role: 'BL', batting: 25, bowling: 68, style: 'N', isForeign: true, traits: ['fbs'] },
    { id: 'int-nep-14', name: 'Manish Chaudhary', age: 23, nationality: 'Nepal', role: 'BT', batting: 60, bowling: 18, style: 'N', isForeign: true },
    { id: 'int-nep-15', name: 'Santosh Joshi', age: 24, nationality: 'Nepal', role: 'AR', batting: 55, bowling: 58, style: 'N', isForeign: true, traits: ['m'] },

    // 🇳🇦 NAMIBIA (15 Players)
    { id: 'int-nam-1', name: 'Petrus Amutenya', age: 27, nationality: 'Namibia', role: 'BT', batting: 66, bowling: 18, style: 'N', isForeign: true, pos: 'OP' },
    { id: 'int-nam-2', name: 'Johannes Koortzen', age: 26, nationality: 'Namibia', role: 'BT', batting: 64, bowling: 20, style: 'A', isForeign: true, pos: 'OP' },
    { id: 'int-nam-3', name: 'Elton Uiseb', age: 25, nationality: 'Namibia', role: 'BT', batting: 65, bowling: 22, style: 'N', isForeign: true },
    { id: 'int-nam-4', name: 'Ruben Shikongo', age: 24, nationality: 'Namibia', role: 'BT', batting: 62, bowling: 18, style: 'D', isForeign: true },
    { id: 'int-nam-5', name: 'Wilhelm Brandt', age: 28, nationality: 'Namibia', role: 'WK', batting: 63, bowling: 69, style: 'N', isForeign: true },
    { id: 'int-nam-6', name: 'Danie Strauss', age: 25, nationality: 'Namibia', role: 'WK', batting: 60, bowling: 68, style: 'D', isForeign: true },
    { id: 'int-nam-7', name: 'Simon Scholtz', age: 28, nationality: 'Namibia', role: 'AR', batting: 60, bowling: 62, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-nam-8', name: 'Tobias Hamutenya', age: 26, nationality: 'Namibia', role: 'AR', batting: 58, bowling: 60, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-nam-9', name: 'Ben Shilongo', age: 25, nationality: 'Namibia', role: 'SB', batting: 40, bowling: 69, style: 'N', isForeign: true, traits: ['ls'] },
    { id: 'int-nam-10', name: 'Jason Erasmus', age: 24, nationality: 'Namibia', role: 'SB', batting: 38, bowling: 68, style: 'D', isForeign: true, traits: ['laos'] },
    { id: 'int-nam-11', name: 'Karl Ndinelao', age: 28, nationality: 'Namibia', role: 'BL', batting: 28, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-nam-12', name: 'Andre Beukes', age: 26, nationality: 'Namibia', role: 'BL', batting: 26, bowling: 69, style: 'D', isForeign: true, traits: ['fbs'] },
    { id: 'int-nam-13', name: 'Hendrik Davids', age: 25, nationality: 'Namibia', role: 'BL', batting: 25, bowling: 69, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-nam-14', name: 'Festus Iipinge', age: 23, nationality: 'Namibia', role: 'BT', batting: 60, bowling: 18, style: 'N', isForeign: true },
    { id: 'int-nam-15', name: 'Leonard Katjirua', age: 25, nationality: 'Namibia', role: 'AR', batting: 55, bowling: 58, style: 'N', isForeign: true, traits: ['fb'] },

    // 🇴🇲 OMAN (15 Players)
    { id: 'int-omn-1', name: 'Faisal Al-Harthy', age: 27, nationality: 'Oman', role: 'BT', batting: 66, bowling: 18, style: 'N', isForeign: true, pos: 'OP' },
    { id: 'int-omn-2', name: 'Sultan Al-Balushi', age: 26, nationality: 'Oman', role: 'BT', batting: 64, bowling: 20, style: 'A', isForeign: true, pos: 'OP' },
    { id: 'int-omn-3', name: 'Nasser Al-Rashdi', age: 25, nationality: 'Oman', role: 'BT', batting: 65, bowling: 22, style: 'N', isForeign: true },
    { id: 'int-omn-4', name: 'Khalid Al-Habsi', age: 28, nationality: 'Oman', role: 'BT', batting: 62, bowling: 18, style: 'D', isForeign: true },
    { id: 'int-omn-5', name: 'Yusuf Al-Mandhari', age: 29, nationality: 'Oman', role: 'WK', batting: 63, bowling: 69, style: 'N', isForeign: true },
    { id: 'int-omn-6', name: 'Hamdan Al-Saadi', age: 25, nationality: 'Oman', role: 'WK', batting: 60, bowling: 68, style: 'D', isForeign: true },
    { id: 'int-omn-7', name: 'Zaid Al-Lawati', age: 28, nationality: 'Oman', role: 'AR', batting: 60, bowling: 62, style: 'N', isForeign: true, traits: ['os'] },
    { id: 'int-omn-8', name: 'Imran Farooq', age: 27, nationality: 'Oman', role: 'AR', batting: 58, bowling: 60, style: 'D', isForeign: true, traits: ['mv'] },
    { id: 'int-omn-9', name: 'Bilal Khan', age: 26, nationality: 'Oman', role: 'SB', batting: 42, bowling: 69, style: 'N', isForeign: true, traits: ['ls'] },
    { id: 'int-omn-10', name: 'Shoaib Malik', age: 24, nationality: 'Oman', role: 'SB', batting: 38, bowling: 68, style: 'D', isForeign: true, traits: ['laos'] },
    { id: 'int-omn-11', name: 'Aamir Kaleem', age: 28, nationality: 'Oman', role: 'BL', batting: 28, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-omn-12', name: 'Kashif Ali', age: 26, nationality: 'Oman', role: 'BL', batting: 26, bowling: 69, style: 'D', isForeign: true, traits: ['fbs'] },
    { id: 'int-omn-13', name: 'Fayyaz Butt', age: 25, nationality: 'Oman', role: 'BL', batting: 25, bowling: 69, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-omn-14', name: 'Rizwan Khan', age: 23, nationality: 'Oman', role: 'BT', batting: 60, bowling: 18, style: 'N', isForeign: true },
    { id: 'int-omn-15', name: 'Junaid Siddiqi', age: 25, nationality: 'Oman', role: 'AR', batting: 55, bowling: 58, style: 'N', isForeign: true, traits: ['fb'] },

    // 🇨🇦 CANADA (15 Players)
    { id: 'int-can-1', name: 'Harpreet Singh', age: 28, nationality: 'Canada', role: 'BT', batting: 68, bowling: 18, style: 'A', isForeign: true, pos: 'OP' },
    { id: 'int-can-2', name: 'Maninder Gill', age: 27, nationality: 'Canada', role: 'BT', batting: 66, bowling: 20, style: 'N', isForeign: true, pos: 'OP' },
    { id: 'int-can-3', name: 'Arjun Patel', age: 25, nationality: 'Canada', role: 'BT', batting: 65, bowling: 22, style: 'N', isForeign: true },
    { id: 'int-can-4', name: 'Rohan Desai', age: 26, nationality: 'Canada', role: 'BT', batting: 62, bowling: 18, style: 'D', isForeign: true },
    { id: 'int-can-5', name: 'Navdeep Kaur', age: 29, nationality: 'Canada', role: 'WK', batting: 64, bowling: 69, style: 'N', isForeign: true },
    { id: 'int-can-6', name: 'Kunal Shah', age: 24, nationality: 'Canada', role: 'WK', batting: 60, bowling: 68, style: 'D', isForeign: true },
    { id: 'int-can-7', name: 'Amit Verma', age: 28, nationality: 'Canada', role: 'AR', batting: 60, bowling: 62, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-can-8', name: 'Sandeep Joshi', age: 27, nationality: 'Canada', role: 'AR', batting: 58, bowling: 60, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-can-9', name: 'Yuvraj Rana', age: 25, nationality: 'Canada', role: 'SB', batting: 40, bowling: 69, style: 'N', isForeign: true, traits: ['ls'] },
    { id: 'int-can-10', name: 'Iqbal Khan', age: 24, nationality: 'Canada', role: 'SB', batting: 38, bowling: 68, style: 'D', isForeign: true, traits: ['laos'] },
    { id: 'int-can-11', name: 'Jason Edwards', age: 28, nationality: 'Canada', role: 'BL', batting: 28, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-can-12', name: 'Mark Thompson', age: 26, nationality: 'Canada', role: 'BL', batting: 26, bowling: 69, style: 'D', isForeign: true, traits: ['fbs'] },
    { id: 'int-can-13', name: 'Paul McKenzie', age: 25, nationality: 'Canada', role: 'BL', batting: 25, bowling: 69, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-can-14', name: 'Ritik Malhotra', age: 23, nationality: 'Canada', role: 'BT', batting: 62, bowling: 18, style: 'N', isForeign: true },
    { id: 'int-can-15', name: 'Sameer Ali', age: 25, nationality: 'Canada', role: 'AR', batting: 55, bowling: 58, style: 'N', isForeign: true, traits: ['fb'] },

    // 🇦🇪 UAE (15 Players)
    { id: 'int-uae-1', name: 'Muhammad Ayaan', age: 27, nationality: 'UAE', role: 'BT', batting: 68, bowling: 18, style: 'A', isForeign: true, pos: 'OP' },
    { id: 'int-uae-2', name: 'Rohan Mustafa', age: 33, nationality: 'UAE', role: 'BT', batting: 66, bowling: 20, style: 'N', isForeign: true, pos: 'OP', traits: ['laos'] },
    { id: 'int-uae-3', name: 'Aryan Lakra', age: 24, nationality: 'UAE', role: 'BT', batting: 65, bowling: 22, style: 'N', isForeign: true },
    { id: 'int-uae-4', name: 'Alishan Sharafu', age: 23, nationality: 'UAE', role: 'BT', batting: 62, bowling: 18, style: 'D', isForeign: true },
    { id: 'int-uae-5', name: 'Vriitya Aravind', age: 24, nationality: 'UAE', role: 'WK', batting: 64, bowling: 69, style: 'N', isForeign: true },
    { id: 'int-uae-6', name: 'Kunal Mehta', age: 26, nationality: 'UAE', role: 'WK', batting: 60, bowling: 68, style: 'D', isForeign: true },
    { id: 'int-uae-7', name: 'Basil Hameed', age: 30, nationality: 'UAE', role: 'AR', batting: 60, bowling: 62, style: 'N', isForeign: true, traits: ['os'] },
    { id: 'int-uae-8', name: 'Zawar Farid', age: 27, nationality: 'UAE', role: 'AR', batting: 58, bowling: 60, style: 'D', isForeign: true, traits: ['mv'] },
    { id: 'int-uae-9', name: 'Aayan Afzal', age: 22, nationality: 'UAE', role: 'SB', batting: 42, bowling: 69, style: 'N', isForeign: true, traits: ['laos'] },
    { id: 'int-uae-10', name: 'Haider Ali', age: 25, nationality: 'UAE', role: 'SB', batting: 38, bowling: 68, style: 'D', isForeign: true, traits: ['ls'] },
    { id: 'int-uae-11', name: 'Junaid Siddique', age: 28, nationality: 'UAE', role: 'BL', batting: 28, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-uae-12', name: 'Zahoor Khan', age: 32, nationality: 'UAE', role: 'BL', batting: 26, bowling: 69, style: 'D', isForeign: true, traits: ['mv'] },
    { id: 'int-uae-13', name: 'Akif Raja', age: 27, nationality: 'UAE', role: 'BL', batting: 25, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-uae-14', name: 'Ashwanth Venkataraman', age: 24, nationality: 'UAE', role: 'BT', batting: 62, bowling: 18, style: 'N', isForeign: true },
    { id: 'int-uae-15', name: 'Sabir Ali', age: 26, nationality: 'UAE', role: 'AR', batting: 55, bowling: 58, style: 'N', isForeign: true, traits: ['mv'] },

    // 🇧🇩 BANGLADESH (20 Players)
    { id: 'int-ban-1', name: 'Tamim Rashed', age: 32, nationality: 'Bangladesh', role: 'BT', batting: 69, bowling: 15, style: 'A', isForeign: true, pos: 'OP' },
    { id: 'int-ban-2', name: 'Nafis Rahman', age: 27, nationality: 'Bangladesh', role: 'BT', batting: 68, bowling: 18, style: 'N', isForeign: true, pos: 'OP' },
    { id: 'int-ban-3', name: 'Shahriar Islam', age: 29, nationality: 'Bangladesh', role: 'BT', batting: 69, bowling: 20, style: 'N', isForeign: true },
    { id: 'int-ban-4', name: 'Mehedi Hasan', age: 26, nationality: 'Bangladesh', role: 'AR', batting: 64, bowling: 66, style: 'NA', isForeign: true, traits: ['os'] },
    { id: 'int-ban-5', name: 'Anik Chowdhury', age: 25, nationality: 'Bangladesh', role: 'BT', batting: 65, bowling: 15, style: 'D', isForeign: true },
    { id: 'int-ban-6', name: 'Rafiul Karim', age: 28, nationality: 'Bangladesh', role: 'WK', batting: 66, bowling: 69, style: 'N', isForeign: true },
    { id: 'int-ban-7', name: 'Mahmudul Haque', age: 24, nationality: 'Bangladesh', role: 'WK', batting: 62, bowling: 68, style: 'D', isForeign: true },
    { id: 'int-ban-8', name: 'Imran Hossain', age: 27, nationality: 'Bangladesh', role: 'AR', batting: 60, bowling: 62, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-ban-9', name: 'Shakib Noor', age: 34, nationality: 'Bangladesh', role: 'AR', batting: 68, bowling: 69, style: 'NA', isForeign: true, traits: ['laos'] },
    { id: 'int-ban-10', name: 'Nazmul Kabir', age: 26, nationality: 'Bangladesh', role: 'AR', batting: 58, bowling: 60, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-ban-11', name: 'Rakib Uddin', age: 25, nationality: 'Bangladesh', role: 'SB', batting: 42, bowling: 69, style: 'N', isForeign: true, traits: ['ls'] },
    { id: 'int-ban-12', name: 'Mizanur Rahman', age: 28, nationality: 'Bangladesh', role: 'SB', batting: 38, bowling: 69, style: 'D', isForeign: true, traits: ['laos'] },
    { id: 'int-ban-13', name: 'Taskin Alam', age: 29, nationality: 'Bangladesh', role: 'BL', batting: 28, bowling: 69, style: 'A', isForeign: true, traits: ['fb'] },
    { id: 'int-ban-14', name: 'Rubel Hasan', age: 31, nationality: 'Bangladesh', role: 'BL', batting: 26, bowling: 69, style: 'N', isForeign: true, traits: ['fbs'] },
    { id: 'int-ban-15', name: 'Fahim Sarkar', age: 25, nationality: 'Bangladesh', role: 'BL', batting: 25, bowling: 69, style: 'D', isForeign: true, traits: ['mv'] },
    { id: 'int-ban-16', name: 'Sajid Mahmud', age: 24, nationality: 'Bangladesh', role: 'BL', batting: 24, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-ban-17', name: 'Tareq Aziz', age: 23, nationality: 'Bangladesh', role: 'BT', batting: 63, bowling: 18, style: 'N', isForeign: true },
    { id: 'int-ban-18', name: 'Aminul Islam', age: 25, nationality: 'Bangladesh', role: 'AR', batting: 55, bowling: 58, style: 'N', isForeign: true, traits: ['ls'] },
    { id: 'int-ban-19', name: 'Zahid Mia', age: 24, nationality: 'Bangladesh', role: 'SB', batting: 40, bowling: 68, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-ban-20', name: 'Hasib Mollah', age: 23, nationality: 'Bangladesh', role: 'BL', batting: 22, bowling: 69, style: 'N', isForeign: true, traits: ['fbs'] },

    // 🇦🇫 AFGHANISTAN (20 Players)
    { id: 'int-afg-1', name: 'Ahmad Shahzad', age: 31, nationality: 'Afghanistan', role: 'BT', batting: 69, bowling: 15, style: 'A', isForeign: true, pos: 'OP' },
    { id: 'int-afg-2', name: 'Noor Zaman', age: 26, nationality: 'Afghanistan', role: 'BT', batting: 69, bowling: 18, style: 'N', isForeign: true, pos: 'OP' },
    { id: 'int-afg-3', name: 'Rahmat Akbari', age: 29, nationality: 'Afghanistan', role: 'BT', batting: 69, bowling: 20, style: 'NA', isForeign: true },
    { id: 'int-afg-4', name: 'Hashmat Farooq', age: 28, nationality: 'Afghanistan', role: 'BT', batting: 68, bowling: 15, style: 'D', isForeign: true },
    { id: 'int-afg-5', name: 'Najibullah Khan', age: 27, nationality: 'Afghanistan', role: 'BT', batting: 69, bowling: 18, style: 'A', isForeign: true },
    { id: 'int-afg-6', name: 'Ikram Alvi', age: 25, nationality: 'Afghanistan', role: 'WK', batting: 66, bowling: 69, style: 'N', isForeign: true },
    { id: 'int-afg-7', name: 'Zia Rahimi', age: 24, nationality: 'Afghanistan', role: 'WK', batting: 62, bowling: 69, style: 'D', isForeign: true },
    { id: 'int-afg-8', name: 'Gulbadin Hamid', age: 32, nationality: 'Afghanistan', role: 'AR', batting: 65, bowling: 64, style: 'NA', isForeign: true, traits: ['mv'] },
    { id: 'int-afg-9', name: 'Karim Jan', age: 26, nationality: 'Afghanistan', role: 'AR', batting: 60, bowling: 62, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-afg-10', name: 'Shafiq Noor', age: 25, nationality: 'Afghanistan', role: 'AR', batting: 58, bowling: 60, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-afg-11', name: 'Rashid Zahir', age: 26, nationality: 'Afghanistan', role: 'SB', batting: 42, bowling: 69, style: 'N', isForeign: true, traits: ['ls'] },
    { id: 'int-afg-12', name: 'Mujeeb Latif', age: 24, nationality: 'Afghanistan', role: 'SB', batting: 38, bowling: 69, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-afg-13', name: 'Naveed Ahmad', age: 28, nationality: 'Afghanistan', role: 'BL', batting: 28, bowling: 69, style: 'A', isForeign: true, traits: ['fbs'] },
    { id: 'int-afg-14', name: 'Fazal Haq', age: 25, nationality: 'Afghanistan', role: 'BL', batting: 26, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-afg-15', name: 'Hamza Sadiq', age: 27, nationality: 'Afghanistan', role: 'BL', batting: 24, bowling: 69, style: 'D', isForeign: true, traits: ['mv'] },
    { id: 'int-afg-16', name: 'Yasir Khalil', age: 24, nationality: 'Afghanistan', role: 'BL', batting: 25, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-afg-17', name: 'Samiullah Noor', age: 25, nationality: 'Afghanistan', role: 'BT', batting: 64, bowling: 18, style: 'N', isForeign: true },
    { id: 'int-afg-18', name: 'Farid Khan', age: 26, nationality: 'Afghanistan', role: 'AR', batting: 55, bowling: 58, style: 'N', isForeign: true, traits: ['laos'] },
    { id: 'int-afg-19', name: 'Qais Shah', age: 24, nationality: 'Afghanistan', role: 'SB', batting: 40, bowling: 69, style: 'D', isForeign: true, traits: ['ls'] },
    { id: 'int-afg-20', name: 'Bilal Azizi', age: 23, nationality: 'Afghanistan', role: 'BL', batting: 22, bowling: 69, style: 'N', isForeign: true, traits: ['fbs'] },

    // 🇮🇪 IRELAND (20 Players)
    { id: 'int-ire-1', name: 'Liam O’Connor', age: 28, nationality: 'Ireland', role: 'BT', batting: 68, bowling: 20, style: 'N', isForeign: true, pos: 'OP' },
    { id: 'int-ire-2', name: 'Sean Murphy', age: 27, nationality: 'Ireland', role: 'BT', batting: 66, bowling: 18, style: 'A', isForeign: true, pos: 'OP' },
    { id: 'int-ire-3', name: 'Patrick Doyle', age: 26, nationality: 'Ireland', role: 'BT', batting: 65, bowling: 22, style: 'N', isForeign: true },
    { id: 'int-ire-4', name: 'Conor Walsh', age: 25, nationality: 'Ireland', role: 'BT', batting: 64, bowling: 18, style: 'D', isForeign: true },
    { id: 'int-ire-5', name: 'Ryan McBride', age: 28, nationality: 'Ireland', role: 'BT', batting: 67, bowling: 20, style: 'N', isForeign: true },
    { id: 'int-ire-6', name: 'Kevin Byrne', age: 29, nationality: 'Ireland', role: 'WK', batting: 65, bowling: 69, style: 'N', isForeign: true },
    { id: 'int-ire-7', name: 'Eoin Flannery', age: 24, nationality: 'Ireland', role: 'WK', batting: 62, bowling: 68, style: 'D', isForeign: true },
    { id: 'int-ire-8', name: 'Mark O’Neill', age: 28, nationality: 'Ireland', role: 'AR', batting: 60, bowling: 62, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-ire-9', name: 'David Keane', age: 27, nationality: 'Ireland', role: 'AR', batting: 58, bowling: 64, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-ire-10', name: 'Thomas Reid', age: 25, nationality: 'Ireland', role: 'AR', batting: 55, bowling: 60, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-ire-11', name: 'Shane Kelly', age: 26, nationality: 'Ireland', role: 'SB', batting: 40, bowling: 69, style: 'D', isForeign: true, traits: ['ls'] },
    { id: 'int-ire-12', name: 'Brian Nolan', age: 25, nationality: 'Ireland', role: 'SB', batting: 38, bowling: 68, style: 'N', isForeign: true, traits: ['laos'] },
    { id: 'int-ire-13', name: 'Luke Patterson', age: 28, nationality: 'Ireland', role: 'BL', batting: 28, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-ire-14', name: 'Aaron Hughes', age: 26, nationality: 'Ireland', role: 'BL', batting: 26, bowling: 69, style: 'D', isForeign: true, traits: ['fbs'] },
    { id: 'int-ire-15', name: 'Calum Scott', age: 25, nationality: 'Ireland', role: 'BL', batting: 25, bowling: 69, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-ire-16', name: 'Nathan Boyd', age: 24, nationality: 'Ireland', role: 'BL', batting: 24, bowling: 68, style: 'D', isForeign: true, traits: ['fb'] },
    { id: 'int-ire-17', name: 'Declan Finn', age: 23, nationality: 'Ireland', role: 'BT', batting: 63, bowling: 18, style: 'N', isForeign: true },
    { id: 'int-ire-18', name: 'Ciaran White', age: 25, nationality: 'Ireland', role: 'AR', batting: 55, bowling: 58, style: 'N', isForeign: true, traits: ['os'] },
    { id: 'int-ire-19', name: 'Paul Rooney', age: 26, nationality: 'Ireland', role: 'SB', batting: 42, bowling: 66, style: 'D', isForeign: true, traits: ['ls'] },
    { id: 'int-ire-20', name: 'Ross Daly', age: 23, nationality: 'Ireland', role: 'BL', batting: 22, bowling: 67, style: 'N', isForeign: true, traits: ['mv'] },

    // 🇿🇼 ZIMBABWE (20 Players)
    { id: 'int-zim-1', name: 'Tawanda Moyo', age: 28, nationality: 'Zimbabwe', role: 'BT', batting: 68, bowling: 18, style: 'A', isForeign: true, pos: 'OP' },
    { id: 'int-zim-2', name: 'Blessing Ncube', age: 27, nationality: 'Zimbabwe', role: 'BT', batting: 66, bowling: 20, style: 'N', isForeign: true, pos: 'OP' },
    { id: 'int-zim-3', name: 'Sean Mutasa', age: 25, nationality: 'Zimbabwe', role: 'BT', batting: 65, bowling: 18, style: 'N', isForeign: true },
    { id: 'int-zim-4', name: 'Craig Chuma', age: 26, nationality: 'Zimbabwe', role: 'BT', batting: 64, bowling: 15, style: 'D', isForeign: true },
    { id: 'int-zim-5', name: 'Elton Sibanda', age: 29, nationality: 'Zimbabwe', role: 'BT', batting: 67, bowling: 22, style: 'NA', isForeign: true },
    { id: 'int-zim-6', name: 'Farai Dube', age: 28, nationality: 'Zimbabwe', role: 'WK', batting: 65, bowling: 69, style: 'N', isForeign: true },
    { id: 'int-zim-7', name: 'Kelvin Zororo', age: 24, nationality: 'Zimbabwe', role: 'WK', batting: 60, bowling: 68, style: 'D', isForeign: true },
    { id: 'int-zim-8', name: 'Ryan Mpofu', age: 28, nationality: 'Zimbabwe', role: 'AR', batting: 60, bowling: 64, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-zim-9', name: 'Tinashe Mhlanga', age: 26, nationality: 'Zimbabwe', role: 'AR', batting: 58, bowling: 62, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-zim-10', name: 'Donald Maposa', age: 25, nationality: 'Zimbabwe', role: 'AR', batting: 55, bowling: 60, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-zim-11', name: 'Shingirai Chirwa', age: 26, nationality: 'Zimbabwe', role: 'SB', batting: 40, bowling: 69, style: 'D', isForeign: true, traits: ['ls'] },
    { id: 'int-zim-12', name: 'Wisdom Marufu', age: 25, nationality: 'Zimbabwe', role: 'SB', batting: 38, bowling: 68, style: 'N', isForeign: true, traits: ['laos'] },
    { id: 'int-zim-13', name: 'Victor Mupfudza', age: 28, nationality: 'Zimbabwe', role: 'BL', batting: 28, bowling: 69, style: 'N', isForeign: true, traits: ['fb'] },
    { id: 'int-zim-14', name: 'Carlton Mavunga', age: 26, nationality: 'Zimbabwe', role: 'BL', batting: 26, bowling: 69, style: 'D', isForeign: true, traits: ['fbs'] },
    { id: 'int-zim-15', name: 'Nigel Bvute', age: 25, nationality: 'Zimbabwe', role: 'BL', batting: 25, bowling: 69, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-zim-16', name: 'Simba Zenda', age: 24, nationality: 'Zimbabwe', role: 'BL', batting: 24, bowling: 68, style: 'D', isForeign: true, traits: ['fb'] },
    { id: 'int-zim-17', name: 'Kuda Nyathi', age: 23, nationality: 'Zimbabwe', role: 'BT', batting: 63, bowling: 18, style: 'N', isForeign: true },
    { id: 'int-zim-18', name: 'Peter Hondo', age: 25, nationality: 'Zimbabwe', role: 'AR', batting: 55, bowling: 58, style: 'N', isForeign: true, traits: ['mv'] },
    { id: 'int-zim-19', name: 'Tapiwa Chigumba', age: 26, nationality: 'Zimbabwe', role: 'SB', batting: 42, bowling: 66, style: 'D', isForeign: true, traits: ['os'] },
    { id: 'int-zim-20', name: 'Leonard Chirwa', age: 22, nationality: 'Zimbabwe', role: 'BL', batting: 22, bowling: 67, style: 'N', isForeign: true, traits: ['fbs'] },
];

export const RAW_INTERNATIONAL_ALL: RawPlayerData[] = [
    ...RAW_INTERNATIONAL_PART1,
    ...RAW_INTERNATIONAL_PART2
];
